; HEADER_BLOCK_START
; generated by OrcaSlicer 2.5.0-dev on 2026-10-01 at 08:57:05
; model printing time: 11m 10s; total estimated time: 12m 0s
; total layer number: 3
; HEADER_BLOCK_END

M83
; CHANGE_LAYER
; FEATURE: Custom
G1 X5 Y5 E0.4 F1800
; printing object Cube id:1111 copy 0
; WIPE_START
G1 X5 Y6 E-0.2 F2400
; WIPE_END
; start printing object, unique label id: 7
M624 AQAAAAAAAAA=
G1 X6 Y6 E0.2 F1800 ; recovers the wipe
; FEATURE: Outer wall
G1 X10 Y10 E1.2
G1 X11 Y10 E-0.8 F2400
G1 E0.8 F1800
; FEATURE: Support
G1 X12 Y10 E2.0
; FEATURE: Support interface
G1 X13 Y10 E0.5
M625
; stop printing object Cube id:1111 copy 0
; stop printing object, unique label id: 7
; printing object Cube id:1111 copy 1
; start printing object, unique label id: 12
M624 AQAAAAAAAAA=
; FEATURE: Sparse infill
G1 X14 Y10 E1.5
;feature:support
G1 X15 Y10 E1.0
M625
; stop printing object Cube id:1111 copy 1
; stop printing object, unique label id: 12
; FEATURE: Brim
G1 X1 Y1 E0.3
; CHANGE_LAYER
; start printing object, unique label id: 7
M624 AQAAAAAAAAA=
; FEATURE: Inner wall
G1 X16 Y10 E0.7
M625
; stop printing object Other id:9 copy 9
; stop printing object Cube id:1111 copy 0
; stop printing object, unique label id: 7
; start printing object, unique label id: 031
M624 AQAAAAAAAAA=
; FEATURE: Top surface
G1 X17 Y10 E0.9
M625
; stop printing object, unique label id: 031
; start printing object, unique label id: 21
; FEATURE: Internal solid infill
G1 X18 Y10 E0.6
M625
; stop printing object My Part v2 id:2222 copy 0
; stop printing object, unique label id: 21
; FEATURE: Prime tower
G1 X19 Y10 E0.5
; FEATURE:
G1 X20 Y10 E0.1
; filament used [mm] = 100.00
; filament used [cm3] = 0.24
; filament used [g] = 12.00
; total filament used [g] = 12.00
; total layers count = 3
; estimated first layer printing time (normal mode) = 1m 5s
; estimated printing time (normal mode) = 12m 10s
; CONFIG_BLOCK_START
; filament_settings_id = "Generic PETG"
; filament_type = PETG
; filament_vendor = "Generic"
; filament_colour = #FFFFFF
; filament_density = 1.27
; filament_diameter = 1.75
; printer_model = Bambu Lab P2S
; nozzle_diameter = 0.4
; layer_height = 0.2
; CONFIG_BLOCK_END
