; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.0 on 2026-09-01 at 10:00:00 UTC
; HEADER_BLOCK_END

EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0 CENTER=50,50 POLYGON=[[1,1],[2,2]]
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_1 CENTER=150,50 POLYGON=[[1,1],[2,2]]
EXCLUDE_OBJECT_DEFINE NAME=Bracket_id_2.stl CENTER=100,150 POLYGON=[[1,1],[2,2]] ; third part
M83 ; relative extrusion
T0
G92 E0
G10
G11
G1 F3000
G92 X0 Y0
;TYPE:Skirt
G1 X5 Y5 E0.8 F1800
EXCLUDE_OBJECT_START NAME=Cube_id_0
;TYPE:Outer wall
G1 X10 Y10 E1.2 ; wall
G1 X11 Y10 E-0.8 F2400
G0 X50 Y50 F9000
G1 E0.8 F1800
G1 X12 Y10 E0.5
   
G1 X12 Y11 E0 ; zero extrusion is not material
G1 X12 Y12 E-1.0
G1 X12 Y13 E0.4
g1 x12 y14 e0.9 ; lower-case command, recovery 0.6 then 0.3 consumed
;TYPE:Sparse infill
G1 X13 Y10 E2.25
G2 X14 Y11 I1 J0 E.5 ; arc with a bare fraction
	
EXCLUDE_OBJECT_END
G1 X14 Y10 E0.4 ; no object here
;TYPE:Brim
G1 X1 Y1 E1.
;TYPE:
G1 X2 Y1 E0.2 ; still brim, an empty TYPE keeps the role
G1 X3 Y1 ;E9 only a comment mentions E
M82 ; absolute extrusion
T1
T1 ; same tool again is not a change
G92 E0 ; reset tool 1
;TYPE:Prime tower
G1 X100 Y100 E2.0
G1 X101 Y100 E1.0
G1 X101 Y100 E2.0
EXCLUDE_OBJECT_START NAME=Cube_id_1
;TYPE:Support
G1 X102 Y100 E3.5 ; with a comment
;TYPE:Support interface
G1 X103 Y100 E4.0
;TYPE:Internal solid infill
G1 X104 Y100 E5.25
G92 E0
G1 X105 Y100 E0.75
EXCLUDE_OBJECT_END
; TYPE: Wipe tower
G1 X106 Y100 E1.5
EXCLUDE_OBJECT_START NAME=Bracket_id_2.stl
;TYPE:Support
G1 X107 Y100 E2.0
EXCLUDE_OBJECT_END
T0
G92 E0
;TYPE:Outer wall
EXCLUDE_OBJECT_START NAME=Cube_id_0
G1 X1 Y2 E1.1
G1 X1 Y3 E2.35
EXCLUDE_OBJECT_END
T0
M83
;TYPE:Sparse infill
G1 X1 Y4 E0.65
G92 E0
M1 S1
G1 X9 E0.1 ; tool 0, relative
; filament used [mm] = 100.00,60.00
; filament used [cm3] = 0.24,0.14
; filament used [g] = 3.00,1.80
; total filament used [g] = 4.80
; total layers count = 5
; estimated first layer printing time (normal mode) = 1m 5s
; estimated printing time (normal mode) = 12m 10s
; CONFIG_BLOCK_START
; filament_settings_id = "Generic PETG";"Generic PLA"
; filament_type = PETG;PLA
; filament_vendor = "Generic";"Bambu Lab"
; filament_colour = #FFFFFF;#000000
; filament_density = 1.27,1.24
; filament_diameter = 1.75,1.75
; printer_model = Bambu Lab P1S
; nozzle_diameter = 0.4
; layer_height = 0.2
; CONFIG_BLOCK_END
