"""A slice is read where it lies: only its summary and totals travel to the site."""

import json
import threading
import tracemalloc
import zipfile
from pathlib import Path

import pytest

MIB = 1024 * 1024
FIXTURES = Path(__file__).resolve().parents[2] / "backend" / "tests" / "fixtures" / "gcode_toolpath_parity"
PARITY = (
    ("toolpath.gcode", "expected_evidence.json"),
    ("bambu_toolpath.gcode", "bambu_expected_evidence.json"),
)

SLICE_INFO = (
    '<?xml version="1.0" encoding="UTF-8"?><config><plate>'
    '<metadata key="index" value="1"/><metadata key="prediction" value="3150"/>'
    '<metadata key="weight" value="12.5"/>'
    '<filament id="1" type="PLA" color="#FFFFFF" used_m="4" used_g="12.5"/>'
    "</plate></config>"
)


def _walk(plugin_module, text, cuts=()):
    walker = plugin_module.SliceToolpathWalker()
    position = 0
    for cut in (*cuts, len(text)):
        walker.push(text[position:cut])
        position = cut
    return walker.finish()


@pytest.mark.parametrize(("gcode", "expected"), PARITY)
def test_the_plugin_walk_equals_the_backend_walk_of_the_shared_fixtures(
    plugin_module, gcode, expected
):
    """The backend test pins the same JSON to its own walker; neither may drift."""
    text = (FIXTURES / gcode).read_bytes().decode("utf-8")
    want = json.loads((FIXTURES / expected).read_text(encoding="utf-8"))

    assert _walk(plugin_module, text) == want
    # One cut at every offset, so each line end meets a chunk boundary.
    for cut in range(1, len(text)):
        assert _walk(plugin_module, text, (cut,)) == want, "cut at %d" % cut


def _big_gcode(path, size, moves_per_block=20000):
    head = b"; generated by OrcaSlicer 2.4.2\n"
    tail = (
        b"; total filament used [g] = 12.5\n"
        b"; estimated printing time (normal mode) = 1h 0m 0s\n"
        b'; printer_model = "Voron 2.4 350"\n'
    )
    block = b";TYPE:Outer wall\n" + b"G1 X10.5 Y20.25 E0.0123 F1800\n" * moves_per_block
    with open(path, "wb") as fh:
        fh.write(head)
        written = len(head)
        while written < size:
            fh.write(block)
            written += len(block)
        fh.write(tail)
    return path.stat().st_size


def _form(fields):
    return dict(fields)


def test_a_large_gcode_is_cut_to_its_ends_and_never_held_whole(
    plugin_module, monkeypatch, tmp_path
):
    source = tmp_path / "big.gcode"
    size = _big_gcode(source, 24 * MIB)
    monkeypatch.setattr(plugin_module, "_SLICE_READ_CHUNK", 256 * 1024)

    tracemalloc.start()
    try:
        fields, parts = plugin_module.build_slice_excerpt(str(source), "big.gcode")
        _, peak = tracemalloc.get_traced_memory()
    finally:
        tracemalloc.stop()

    form = _form(fields)
    assert form["container"] == "plain_gcode"
    assert form["file_size_bytes"] == str(size)
    assert [(field, len(data)) for field, _, data in parts] == [
        ("head", 1 * MIB),
        ("tail", 4 * MIB),
    ]
    raw = source.read_bytes()
    assert parts[0][2] == raw[: 1 * MIB]
    assert parts[1][2] == raw[-4 * MIB :]
    assert b"total filament used" in parts[1][2]
    # Head and tail are 5 MiB; the file is 24 MiB and was never held whole.
    assert peak < 14 * MIB
    evidence = json.loads(form["toolpath"])
    assert evidence["extrusion_by_tool_role"]["0"]["outer wall"] > 0

    boundary, body = plugin_module.encode_slice_excerpt(fields, parts)
    assert len(body) < 6 * MIB
    assert body.count(("--" + boundary).encode()) == 1 + len(fields) + len(parts)


def test_a_small_gcode_is_sent_whole_and_a_gzip_is_read_through(plugin_module, tmp_path):
    text = (FIXTURES / "toolpath.gcode").read_bytes()
    plain = tmp_path / "small.gcode"
    plain.write_bytes(text)
    import gzip

    packed = tmp_path / "small.gcode.gz"
    packed.write_bytes(gzip.compress(text))

    fields, parts = plugin_module.build_slice_excerpt(str(plain), "small.gcode")
    packed_fields, packed_parts = plugin_module.build_slice_excerpt(
        str(packed), "small.gcode.gz"
    )

    assert [(field, data) for field, _, data in parts] == [("head", text)]
    assert [(field, data) for field, _, data in packed_parts] == [("head", text)]
    expected = (FIXTURES / "expected_evidence.json").read_text(encoding="utf-8")
    assert json.loads(_form(fields)["toolpath"]) == json.loads(expected)
    assert _form(packed_fields)["toolpath"] == _form(fields)["toolpath"]


def _write_3mf(path, entries):
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, data in entries:
            archive.writestr(name, data)


def test_a_sliced_3mf_sends_its_metadata_and_walks_the_plate_without_sending_it(
    plugin_module, tmp_path
):
    plate = (FIXTURES / "toolpath.gcode").read_bytes()
    source = tmp_path / "plates.gcode.3mf"
    _write_3mf(
        source,
        [
            ("Metadata/plate_1.gcode", plate),
            ("Metadata/slice_info.config", SLICE_INFO),
            ("Metadata/project_settings.config", "{}"),
            ("Metadata/plate_1.png", b"\x89PNG\r\n" + b"x" * 50),
            ("3D/3dmodel.model", b"<model>" + b"y" * 4096 + b"</model>"),
        ],
    )

    fields, parts = plugin_module.build_slice_excerpt(str(source), "plates.gcode.3mf")

    form = _form(fields)
    assert form["container"] == "gcode_3mf"
    assert [field for field, _, _ in parts] == ["entry"] * 3
    assert [name for _, name, _ in parts] == [
        "Metadata/slice_info.config",
        "Metadata/project_settings.config",
        "Metadata/plate_1.png",
    ]
    assert all(b"G1 " not in data for _, _, data in parts)
    expected = json.loads((FIXTURES / "expected_evidence.json").read_text(encoding="utf-8"))
    assert json.loads(form["toolpath"]) == {"1": expected}


def test_a_3mf_that_breaks_the_contract_is_refused_before_anything_is_sent(
    plugin_module, tmp_path
):
    without_info = tmp_path / "a.gcode.3mf"
    _write_3mf(without_info, [("Metadata/plate_1.gcode", b"G1 E1\n")])
    not_a_zip = tmp_path / "b.gcode.3mf"
    not_a_zip.write_bytes(b"PK\x03\x04 broken")
    oversized = tmp_path / "c.gcode.3mf"
    _write_3mf(
        oversized,
        [
            ("Metadata/slice_info.config", SLICE_INFO),
            ("Metadata/model_settings.config", b"z" * (2 * MIB)),
        ],
    )
    renamed = tmp_path / "d.gcode"
    _write_3mf(renamed, [("Metadata/slice_info.config", SLICE_INFO)])
    wrong_extension = tmp_path / "e.stl"
    wrong_extension.write_bytes(b"solid")

    def refusal(path, name):
        with pytest.raises(plugin_module.SliceExcerptError) as caught:
            plugin_module.build_slice_excerpt(str(path), name)
        return caught.value.code

    assert refusal(without_info, "a.gcode.3mf") == "ERR_GCODE_EXCERPT_INVALID"
    assert refusal(not_a_zip, "b.gcode.3mf") == "ERR_GCODE_EXCERPT_INVALID"
    assert refusal(oversized, "c.gcode.3mf") == "ERR_GCODE_EXCERPT_TOO_LARGE"
    assert refusal(renamed, "d.gcode") == "ERR_GCODE_EXCERPT_INVALID"
    assert refusal(wrong_extension, "e.stl") == "ERR_GCODE_UNSUPPORTED_FILE"


def test_a_walk_that_does_not_fit_the_contract_still_sends_the_summary(
    plugin_module, tmp_path
):
    roles = "".join(";TYPE:role %d\nG1 X1 E%d.5\n" % (n, n) for n in range(80))
    source = tmp_path / "many.gcode"
    source.write_text("; generated by OrcaSlicer 2.4.2\n" + roles, encoding="utf-8")
    plate = tmp_path / "many.gcode.3mf"
    _write_3mf(
        plate,
        [("Metadata/slice_info.config", SLICE_INFO), ("Metadata/plate_1.gcode", roles)],
    )

    plain_fields, plain_parts = plugin_module.build_slice_excerpt(str(source), "many.gcode")
    plate_fields, plate_parts = plugin_module.build_slice_excerpt(str(plate), "many.gcode.3mf")

    assert "toolpath" not in _form(plain_fields)
    assert [field for field, _, _ in plain_parts] == ["head"]
    assert "toolpath" not in _form(plate_fields)
    assert [name for _, name, _ in plate_parts] == ["Metadata/slice_info.config"]


def test_an_excerpt_over_the_request_cap_is_never_posted(plugin_module, monkeypatch):
    posted = []
    monkeypatch.setattr(
        plugin_module, "_send_multipart", lambda *args, **kwargs: posted.append(args)
    )

    status, body = plugin_module.http_post_slice_excerpt(
        "token", [("file_name", "x.gcode")], [("head", "head.gcode", b"x" * (25 * MIB))]
    )

    assert posted == []
    assert status == 413
    assert json.loads(body)["detail"]["code"] == "ERR_GCODE_EXCERPT_TOO_LARGE"


def _catalog(plugin_module, monkeypatch, tmp_path, entry):
    catalog = plugin_module.FilamentHubCatalog()
    delivered = []
    monkeypatch.setattr(
        catalog, "_deliver", lambda kind, **data: delivered.append((kind, data)) or True
    )
    monkeypatch.setattr(plugin_module, "slice_entry_for_key", lambda key: entry)
    monkeypatch.setattr(plugin_module, "fh_log", lambda message: None)
    return catalog, delivered


def _results(delivered):
    return [data["result"] for kind, data in delivered if kind == "parsed-slice"]


def test_the_page_gets_every_plate_and_the_first_one_for_an_older_page(
    plugin_module, monkeypatch, tmp_path
):
    source = tmp_path / "slice.gcode"
    source.write_bytes((FIXTURES / "toolpath.gcode").read_bytes())
    catalog, delivered = _catalog(
        plugin_module, monkeypatch, tmp_path, {"path": str(source), "name": "slice.gcode"}
    )
    sent = []

    def answer(token, fields, parts):
        sent.append((token, dict(fields), parts))
        return 200, json.dumps({"jobs": [{"plate_index": 1}, {"plate_index": 2}]}).encode()

    monkeypatch.setattr(plugin_module, "http_post_slice_excerpt", answer)

    catalog._parse_slice("k1", "token", str(source), "Cube.gcode")

    [result] = _results(delivered)
    assert result == {
        "sourceKey": "k1",
        "jobs": [{"plate_index": 1}, {"plate_index": 2}],
        "parsed": {"plate_index": 1},
    }
    [(token, form, parts)] = sent
    assert (token, form["file_name"], form["container"]) == ("token", "Cube.gcode", "plain_gcode")
    assert form["file_size_bytes"] == str(source.stat().st_size)


@pytest.mark.parametrize(
    ("status", "body", "expected"),
    [
        (413, b'{"detail":{"code":"ERR_GCODE_EXCERPT_TOO_LARGE"}}',
         {"error": "http", "status": 413, "code": "ERR_GCODE_EXCERPT_TOO_LARGE"}),
        (403, b'{"detail":{"code":"ERR_CALCULATOR_ACCESS_REQUIRED"}}',
         {"error": "http", "status": 403, "code": "ERR_CALCULATOR_ACCESS_REQUIRED"}),
        (502, b"<html>bad gateway</html>", {"error": "http", "status": 502, "code": ""}),
        (0, b"timed out", {"error": "http", "status": 0, "code": ""}),
        (200, b"not json", {"error": "body"}),
        (200, b'{"jobs": []}', {"error": "body"}),
    ],
)
def test_every_failure_reaches_the_page_as_an_explicit_result(
    plugin_module, monkeypatch, tmp_path, status, body, expected
):
    source = tmp_path / "slice.gcode"
    source.write_bytes(b"; generated by OrcaSlicer 2.4.2\nG1 X1 E1\n")
    catalog, delivered = _catalog(
        plugin_module, monkeypatch, tmp_path, {"path": str(source), "name": "slice.gcode"}
    )
    monkeypatch.setattr(
        plugin_module, "http_post_slice_excerpt", lambda *args: (status, body)
    )

    catalog._parse_slice("k2", "token", str(source), "slice.gcode")

    assert _results(delivered) == [dict(expected, sourceKey="k2")]


def test_an_unreadable_slice_and_an_unexpected_crash_are_reported_not_swallowed(
    plugin_module, monkeypatch, tmp_path
):
    source = tmp_path / "slice.gcode"
    source.write_bytes(b"")
    catalog, delivered = _catalog(
        plugin_module, monkeypatch, tmp_path, {"path": str(source), "name": "slice.gcode"}
    )

    catalog._parse_slice("k3", "token", str(source), "slice.gcode")
    catalog._parse_slice("k4", "token", str(tmp_path / "missing.gcode"), "slice.gcode")
    monkeypatch.setattr(
        plugin_module,
        "build_slice_excerpt",
        lambda *args: (_ for _ in ()).throw(ValueError("boom")),
    )
    catalog._parse_slice("k5", "token", str(source), "slice.gcode")

    assert _results(delivered) == [
        {"sourceKey": "k3", "error": "read", "code": "ERR_GCODE_EXCERPT_INVALID"},
        {"sourceKey": "k4", "error": "gone"},
        {"sourceKey": "k5", "error": "read"},
    ]


def test_a_retired_plugin_generation_stops_a_long_read_without_an_answer(
    plugin_module, monkeypatch, tmp_path
):
    source = tmp_path / "slice.gcode"
    _big_gcode(source, 8 * MIB)
    catalog, delivered = _catalog(
        plugin_module, monkeypatch, tmp_path, {"path": str(source), "name": "slice.gcode"}
    )
    monkeypatch.setattr(plugin_module, "_SLICE_READ_CHUNK", 256 * 1024)
    worker = plugin_module.ReusableDaemonWorker("filamenthub-slice-test")
    monkeypatch.setattr(plugin_module, "BACKGROUND_WORKER", worker)
    posted = []
    monkeypatch.setattr(
        plugin_module, "http_post_slice_excerpt", lambda *args: posted.append(args)
    )
    seen_chunks = []
    real_sleep = plugin_module.time.sleep

    def retire_after_first_chunk(seconds):
        seen_chunks.append(seconds)
        if len(seen_chunks) == 2:
            worker.stop(wait_timeout=0)
        real_sleep(0)

    monkeypatch.setattr(plugin_module.time, "sleep", retire_after_first_chunk)
    done = threading.Event()

    def job():
        worker_generation = worker.current_job_generation()
        worker.run_in_generation(
            worker_generation, catalog._parse_slice, "k6", "token", str(source), "slice.gcode"
        )
        done.set()

    assert worker.submit(job)
    assert done.wait(10)

    assert posted == []
    assert _results(delivered) == []
    assert len(seen_chunks) < 8 * MIB // (256 * 1024)
    worker.stop(wait_timeout=0)


def test_only_one_slice_is_read_at_a_time_and_a_free_slot_runs_in_its_own_thread(
    plugin_module, monkeypatch, tmp_path
):
    source = tmp_path / "slice.gcode"
    source.write_bytes(b"; x\n")
    catalog, delivered = _catalog(
        plugin_module, monkeypatch, tmp_path, {"path": str(source), "name": "slice.gcode"}
    )
    started = threading.Event()
    release = threading.Event()
    ran_on = []

    def slow_parse(key, token, path, name):
        ran_on.append(threading.current_thread().name)
        started.set()
        assert release.wait(5)

    monkeypatch.setattr(catalog, "_parse_slice", slow_parse)

    catalog._do_parse_slice("first", "token", "slice.gcode")
    assert started.wait(5)
    catalog._do_parse_slice("second", "token", "slice.gcode")
    release.set()
    for _ in range(100):
        if plugin_module._SLICE_PARSE_LOCK.acquire(False):
            plugin_module._SLICE_PARSE_LOCK.release()
            break
        threading.Event().wait(0.05)

    assert ran_on == ["filamenthub-slice-parse"]
    assert _results(delivered) == [{"sourceKey": "second", "error": "busy"}]


def test_a_slice_whose_file_is_gone_or_without_a_session_is_answered_at_once(
    plugin_module, monkeypatch, tmp_path
):
    catalog, delivered = _catalog(plugin_module, monkeypatch, tmp_path, None)
    catalog._do_parse_slice("gone-key", "token")
    monkeypatch.setattr(
        plugin_module, "slice_entry_for_key", lambda key: {"path": "x", "name": "x.gcode"}
    )
    catalog._do_parse_slice("auth-key", "")

    assert _results(delivered) == [
        {"sourceKey": "gone-key", "error": "gone"},
        {"sourceKey": "auth-key", "error": "auth"},
    ]
