"""Slicing, host storage and runtime resource contracts."""

import os
import re

import pytest

from .filamenthub_plugin_test_support import (
    json,
    _module_with_pages,
    _module_with_slicing,
    SimpleNamespace,
    _slice_storage,
)


def test_a_slice_is_identified_by_the_machine_it_was_made_for(tmp_path):
    """Only what names the slice travels; figures come from reading the file."""
    module, _ = _module_with_slicing()
    gcode = tmp_path / "Cube_PETG.gcode"
    gcode.write_text(
        chr(10).join(
            [
                "; generated by OrcaSlicer 2.4.2 on 2026-07-11 at 10:39:05",
                "G1 X1 Y1 E1",
                "; total filament used [g] = 151.22",
                '; printer_settings_id = "Voron 2.4 350 0.4 nozzle"',
                '; printer_model = "Voron 2.4 350"',
            ]
        ),
        encoding="utf-8",
    )

    identity = module._read_slice_identity(str(gcode))

    assert identity["printer_settings_id"] == "Voron 2.4 350 0.4 nozzle"
    assert identity["printer_model"] == "Voron 2.4 350"
    assert identity["slicer_version"] == "2.4.2"
    # Weights stay out of it: the file is the one source of them.
    assert not any("weight" in key or "seconds" in key for key in identity)

def test_managed_profile_identities_are_written_per_kind_and_tool_once(
    tmp_path, monkeypatch
):
    """One numeric id may exist in three tables; kind and tool keep it exact."""
    module, _ = _module_with_slicing()
    monkeypatch.setattr(module, "DATA_DIR", str(tmp_path))
    monkeypatch.setattr(module, "_user_preset_folder", "default")

    managed = {
        "filament": ("Material", 7),
        "process": ("Process", 7),
        "machine": ("Machine", 7),
    }
    for folder, (name, entity_id) in managed.items():
        target = tmp_path / "user" / "default" / "_local" / "filamenthub" / folder
        target.mkdir(parents=True, exist_ok=True)
        (target / (name + ".json")).write_text(
            json.dumps({"name": name, "bundle_id": "filamenthub:%d" % entity_id}),
            encoding="utf-8",
        )

    config = {
        "filament_settings_id": '"_local/filamenthub/Material";"Generic PETG @System"',
        "print_settings_id": "_local/filamenthub/Process",
        "printer_settings_id": "_local/filamenthub/Machine",
    }
    ctx = SimpleNamespace(config_value=lambda key: config.get(key))
    identities = module._slice_managed_identities(ctx)
    gcode = tmp_path / "managed.gcode"
    gcode.write_text(
        chr(10).join(
            [
                "; generated by OrcaSlicer 2.5.0-dev",
                "; print_settings_id = Process",
                "; printer_settings_id = Machine",
            ]
        ),
        encoding="utf-8",
    )

    assert identities == [
        {"kind": "material_preset", "tool_index": 0, "id": 7},
        {"kind": "print_profile", "tool_index": None, "id": 7},
        {"kind": "printer_profile", "tool_index": None, "id": 7},
    ]
    assert module._append_fhub_slice_identities(str(gcode), identities)
    assert module._append_fhub_slice_identities(str(gcode), identities)

    content = gcode.read_text(encoding="utf-8")
    assert content.count("fhub_identity_v1") == 3
    assert "kind=material_preset;tool=0;id=7" in content
    reported = module._read_slice_identity(str(gcode))
    assert reported["fhub_print_profile_id"] == 7
    assert reported["fhub_printer_profile_id"] == 7

def test_the_path_stays_behind_a_key_the_site_can_ask_with(tmp_path, monkeypatch):
    """A path carries a person's folders, so only a key leaves this machine."""
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "Cube_PETG.gcode"
    gcode.write_text("; generated by OrcaSlicer 2.4.2", encoding="utf-8")

    key = module._remember_slice_path(str(gcode))

    assert key and str(gcode) not in key
    cached = module.slice_path_for_key(key)
    assert cached and cached != str(gcode)
    assert module.slice_entry_for_key(key)["name"] == gcode.name
    assert module.slice_path_for_key("nothing-like-it") is None

    gcode.unlink()
    # The plugin owns a bounded copy, so losing the host's source file must
    # not make a just-reported slice disappear.
    assert module.slice_path_for_key(key) == cached
    os.remove(cached)
    assert module.slice_path_for_key(key) is None

def test_a_slice_sent_to_a_printer_survives_the_host_deleting_it(tmp_path, monkeypatch):
    """Uploading writes a temp file the host removes; a copy keeps it countable."""
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    upload = tmp_path / ".OrcaSlicer.upload.5ca1-0810"
    upload.write_text("; generated by OrcaSlicer 2.4.2", encoding="utf-8")

    key = module._remember_slice_path(str(upload), "Cube_PETG.gcode")
    upload.unlink()

    entry = module.slice_entry_for_key(key)
    assert entry is not None and entry["path"] != str(upload)
    # The copy is named after the key, so the name a person gave the print is
    # what the calculation must be labelled with.
    assert entry["name"] == "Cube_PETG.gcode"
    with open(entry["path"], "r", encoding="utf-8") as fh:
        assert fh.read() == "; generated by OrcaSlicer 2.4.2"

def test_only_the_newest_few_uploads_are_kept(tmp_path, monkeypatch):
    """The cache is a convenience, not an archive of someone's disk."""
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)

    keys = []
    for number in range(module._SLICE_CACHE_FILES + 3):
        upload = tmp_path / (".OrcaSlicer.upload.%d" % number)
        upload.write_text("; slice %d" % number, encoding="utf-8")
        keys.append(module._remember_slice_path(str(upload)))
        upload.unlink()

    kept = [key for key in keys if module.slice_path_for_key(key)]
    assert len(kept) == module._SLICE_CACHE_FILES
    assert keys[-1] in kept

def test_the_reporter_is_registered_only_where_the_host_can_slice():
    """A host without the slicing pipeline must still load the plugin."""
    with_slicing, registered = _module_with_slicing()
    assert with_slicing.FilamentHubSliceReporter is not None
    with_slicing.FilamentHubPlugin().register_capabilities()
    assert with_slicing.FilamentHubSliceReporter in registered


def test_slice_reporting_is_opt_in_before_any_file_or_network_operation(
    tmp_path, monkeypatch
):
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "opt-in.gcode"
    gcode.write_text("; generated by OrcaSlicer", encoding="utf-8")
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({})
    calls = []
    monkeypatch.setattr(module, "_append_fhub_slice_identities", lambda *a: calls.append("append"))
    monkeypatch.setattr(module, "report_slice", lambda *a: calls.append("report"))

    result = reporter.execute(SimpleNamespace(
        step="psGCodePostProcess", gcode_path=str(gcode), output_name="opt-in.gcode"
    ))

    assert result[0] == "skipped"
    assert calls == []
    assert not (tmp_path / "slices.json").exists()
    assert not (tmp_path / "cache").exists()


def test_malformed_or_missing_slice_config_is_safe_default(tmp_path, monkeypatch):
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "disabled.gcode"
    gcode.write_text("G1 X1", encoding="utf-8")
    for config in (
        "not-json", None, "null", "[]", "true", '{"report_slices": false}',
        '{"report_slices": "true"}', '{"report_slices": 1}',
    ):
        reporter = module.FilamentHubSliceReporter()
        if config is not None:
            reporter.get_config = lambda value=config: value
        calls = []
        monkeypatch.setattr(module, "report_slice", lambda *a: calls.append(True))
        result = reporter.execute(SimpleNamespace(
            step="psGCodePostProcess", gcode_path=str(gcode)
        ))
        assert result[0] == "skipped"
        assert calls == []


def test_denied_local_identity_write_prevents_http_report(tmp_path, monkeypatch):
    module, _ = _module_with_slicing()
    gcode = tmp_path / "denied-local.gcode"
    gcode.write_text("G1 X1", encoding="utf-8")
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({"report_slices": True})
    monkeypatch.setattr(module, "_append_fhub_slice_identities", lambda *a: False)
    monkeypatch.setattr(module, "report_slice", lambda *a: pytest.fail("HTTP must not run"))

    result = reporter.execute(SimpleNamespace(
        step="psGCodePostProcess", gcode_path=str(gcode)
    ))

    assert result == ("skipped", module.ui_text("sliceUnreadable"))


def test_slicing_worker_never_opens_the_http_permission_dialog(tmp_path, monkeypatch):
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "permission-pending.gcode"
    gcode.write_text("; generated by OrcaSlicer 2.4.2\nG1 X1", encoding="utf-8")
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({"report_slices": True})
    monkeypatch.setattr(module, "_append_fhub_slice_identities", lambda *a: True)
    monkeypatch.setattr(
        module, "load_saved_auth", lambda: {"accessToken": "test-token"}
    )
    monkeypatch.setattr(module, "plugin_source_instance_id", lambda: "source-instance")
    monkeypatch.setattr(
        module,
        "http_post_json",
        lambda *a: pytest.fail("the slicing worker must not request HTTP permission"),
    )

    result = reporter.execute(SimpleNamespace(
        step="psGCodePostProcess", gcode_path=str(gcode),
        output_name="permission-pending.gcode", host="File",
    ))

    assert result == (
        "success",
        module.ui_text("sliceQueued", name="permission-pending.gcode"),
    )
    assert module._load_slice_index()
    assert len(module._load_slice_report_outbox()) == 1


def test_activation_never_requests_http_permission(monkeypatch):
    module, _ = _module_with_slicing()
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({"report_slices": True})
    monkeypatch.setattr(module, "configure_plugin_storage", lambda: True)
    monkeypatch.setattr(module, "start_plugin_runtime", lambda **_kwargs: True)
    monkeypatch.setattr(
        module, "load_saved_auth", lambda: {"accessToken": "test-token"}
    )
    monkeypatch.setattr(
        module,
        "_urlopen_authorized",
        lambda *_args: pytest.fail("activation must not perform network I/O"),
    )

    reporter.on_load()

    assert module._slice_delivery_target() is None


def test_failed_page_delivery_keeps_the_slice_for_retry(tmp_path, monkeypatch):
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "page-retry.gcode"
    gcode.write_text("; generated by OrcaSlicer 2.4.2\nG1 X1", encoding="utf-8")
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({"report_slices": True})
    monkeypatch.setattr(module, "_append_fhub_slice_identities", lambda *a: True)
    monkeypatch.setattr(
        module, "load_saved_auth", lambda: {"accessToken": "test-token"}
    )
    monkeypatch.setattr(module, "plugin_source_instance_id", lambda: "source-instance")

    result = reporter.execute(SimpleNamespace(
        step="psGCodePostProcess", gcode_path=str(gcode)
    ))

    pending = module._load_slice_report_outbox()
    assert result[0] == "success"
    assert len(pending) == 1
    assert module._acknowledge_slice_reports([]) == 0
    assert module._load_slice_report_outbox() == pending
    assert module._acknowledge_slice_reports([pending[0]["source_key"]]) == 1
    assert module._load_slice_report_outbox() == []


def test_slice_is_queued_before_the_page_signs_in(tmp_path, monkeypatch):
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "signed-out.gcode"
    gcode.write_text("; generated by OrcaSlicer 2.4.2\nG1 X1", encoding="utf-8")
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({"report_slices": True})
    monkeypatch.setattr(module, "_append_fhub_slice_identities", lambda *a: True)
    monkeypatch.setattr(module, "load_saved_auth", lambda: None)
    monkeypatch.setattr(module, "plugin_source_instance_id", lambda: "source-instance")

    result = reporter.execute(SimpleNamespace(
        step="psGCodePostProcess", gcode_path=str(gcode),
        output_name="signed-out.gcode", host="File",
    ))

    assert result == (
        "success",
        module.ui_text("sliceQueued", name="signed-out.gcode"),
    )
    assert [item["file_name"] for item in module._load_slice_report_outbox()] == [
        "signed-out.gcode"
    ]


@pytest.mark.parametrize("failure", ["cache", "index"])
def test_storage_failure_prevents_http_report(tmp_path, monkeypatch, failure):
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "storage-failure.gcode"
    gcode.write_text("; generated by OrcaSlicer 2.4.2\nG1 X1", encoding="utf-8")
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({"report_slices": True})
    monkeypatch.setattr(module, "_append_fhub_slice_identities", lambda *a: True)
    monkeypatch.setattr(module, "load_saved_auth", lambda: {"accessToken": "test-token"})
    posted = []
    monkeypatch.setattr(module, "http_post_json", lambda *a: posted.append(a))
    if failure == "cache":
        monkeypatch.setattr(module, "_cache_slice_file", lambda *a: None)
    else:
        monkeypatch.setattr(
            module, "write_json_atomic", lambda *a, **k: (_ for _ in ()).throw(OSError("denied"))
        )

    result = reporter.execute(SimpleNamespace(
        step="psGCodePostProcess", gcode_path=str(gcode), output_name="named.gcode"
    ))

    assert result[0] == "skipped"
    assert result[1] == module.ui_text("sliceReportFailed")
    assert posted == []


def test_opted_in_report_queues_metadata_without_local_path_or_gcode(
    tmp_path, monkeypatch
):
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "Cube_PETG.gcode"
    gcode.write_text(
        "; generated by OrcaSlicer 2.4.2\n"
        '; printer_settings_id = "Voron 2.4 350"\nG1 X1 Y1 E1\n',
        encoding="utf-8",
    )
    reporter = module.FilamentHubSliceReporter()
    reporter.get_config = lambda: json.dumps({"report_slices": True})
    monkeypatch.setattr(module, "load_saved_auth", lambda: {"accessToken": "test-token"})
    monkeypatch.setattr(module, "plugin_source_instance_id", lambda: "source-instance")
    delivered = []

    class Target:
        def _deliver(self, message_type, **payload):
            delivered.append((message_type, payload))

    module._set_slice_delivery_target(Target())

    result = reporter.execute(SimpleNamespace(
        step="psGCodePostProcess", gcode_path=str(gcode),
        output_name="Cube_PETG.gcode", host="File", config_value=lambda key: None,
    ))

    assert result[0] == "success"
    # Orca runs this capability on its slicing worker while the GUI waits for
    # completion. Calling window.post here marshals to that waiting UI thread
    # and deadlocks export/upload. The page pulls this durable queue later.
    assert delivered == []
    queued = module._load_slice_report_outbox()
    assert len(queued) == 1
    identity = queued[0]
    assert identity["file_name"] == "Cube_PETG.gcode"
    assert identity["source_instance_id"] == "source-instance"
    assert identity["target_host"] == "File"
    assert "source_key" in identity
    assert str(gcode) not in json.dumps(identity)
    assert "G1 X1 Y1 E1" not in json.dumps(identity)
    assert gcode.exists()
    assert module._load_slice_report_outbox() == [identity]


def test_slice_settings_explain_opt_in_endpoint_and_stable_capability_name():
    module, _ = _module_with_slicing()
    reporter = module.FilamentHubSliceReporter()

    html = reporter.get_config_ui()

    assert reporter.get_name() == "filamenthub-slice-reporter"
    assert module.API_BASE + "/orcaslicer/slices" in html
    assert module.ui_text("sliceSettingsPurpose") in html
    assert module.ui_text("sliceSettingsPermission") in html

def test_without_the_pipeline_the_plugin_still_registers_its_window(plugin_module):
    assert plugin_module.FilamentHubSliceReporter is None
    plugin_module.FilamentHubPlugin().register_capabilities()

def test_pages_host_registers_a_tab_instead_of_the_window_action():
    module, registered = _module_with_pages()
    module.FilamentHubPlugin().register_capabilities()
    assert module.FilamentHubPage in registered
    assert module.FilamentHubCatalog not in registered

def test_current_host_defers_runtime_resources_to_capability_lifecycle(monkeypatch):
    module, _ = _module_with_pages(native_lifecycle=True)
    lifecycle = []
    stopped = []
    monkeypatch.setattr(
        module,
        "configure_plugin_storage",
        lambda: lifecycle.append("storage") or True,
    )
    monkeypatch.setattr(
        module,
        "start_plugin_runtime",
        lambda storage_initialized=False: lifecycle.append(
            ("start", storage_initialized)
        ),
    )
    monkeypatch.setattr(module, "stop_plugin_runtime", lambda: stopped.append(True))

    module.FilamentHubPlugin().register_capabilities()
    assert lifecycle == []

    page = module.FilamentHubPage()
    page.on_load()
    page.on_cancelled()
    page.on_unload()

    assert lifecycle == ["storage", ("start", True)]
    assert stopped == [True, True]

def test_old_host_keeps_registration_time_runtime_fallback(monkeypatch):
    module, _ = _module_with_pages(native_lifecycle=False)
    started = []
    monkeypatch.setattr(module, "start_plugin_runtime", lambda: started.append(True))

    module.FilamentHubPlugin().register_capabilities()

    assert started == [True]

def test_runtime_stop_closes_every_owned_resource(plugin_module, monkeypatch):
    stopped = []
    monkeypatch.setattr(
        plugin_module,
        "BACKGROUND_WORKER",
        SimpleNamespace(stop=lambda: stopped.append("worker")),
    )
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_BRIDGE_RUNTIME",
        SimpleNamespace(stop=lambda: stopped.append("bambu")),
    )
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_SCHEDULER",
        SimpleNamespace(stop=lambda: stopped.append("revoke-scheduler")),
    )
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_ACTIVE", True)
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_EPOCH", 1)

    assert plugin_module.stop_plugin_runtime() is True
    assert stopped == ["revoke-scheduler", "worker", "bambu"]
    assert plugin_module._PLUGIN_RUNTIME_ACTIVE is False

def test_runtime_load_starts_pending_bambu_revoke_scheduler(
    plugin_module, monkeypatch
):
    calls = []

    class Worker:
        def activate(self):
            calls.append("activate")

        def stop(self):
            calls.append("stop")

    monkeypatch.setattr(plugin_module, "BACKGROUND_WORKER", Worker())
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_BRIDGE_RUNTIME",
        SimpleNamespace(start=lambda: calls.append("bambu-start"), stop=lambda: None),
    )
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_SCHEDULER",
        SimpleNamespace(
            start=lambda: calls.append("revoke-start"),
            stop=lambda: calls.append("revoke-stop"),
        ),
    )
    monkeypatch.setattr(plugin_module, "refresh_ui_language", lambda: None)
    monkeypatch.setattr(
        plugin_module,
        "load_bambu_config",
        lambda: {"source_instance_id": "fixture", "printers": []},
    )
    monkeypatch.setattr(plugin_module, "repair_local_bundle_parents", lambda: 0)
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_ACTIVE", False)
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_EPOCH", 0)

    assert plugin_module.start_plugin_runtime(storage_initialized=True) is True
    assert calls[:2] == ["activate", "revoke-start"]
    assert plugin_module.stop_plugin_runtime() is True

def test_pages_host_delivers_plugin_messages_through_post_message():
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()

    page._catalog._deliver_sync_result("Synced", 2)

    assert page.posted_messages == [{
        "source": "filamenthub-host",
        "type": "sync-result",
        "text": "Synced",
        "draftCount": 2,
        "operationId": "",
        "scope": "all",
        "status": "success",
        "contours": [],
        "notify": True,
        "connectionReview": False,
    }]


def test_pages_bridge_retries_and_acknowledges_the_local_slice_queue(
    tmp_path, monkeypatch
):
    module, _ = _module_with_pages()
    _slice_storage(module, tmp_path, monkeypatch)
    source_key = "a" * 64
    module._queue_slice_report({
        "file_name": "cube.gcode",
        "source_key": source_key,
        "source_instance_id": "source-instance-1234",
    })
    page = module.FilamentHubPage()
    page.get_ui()
    session = page._catalog._direct_bridge_session

    page.on_message({
        "source": "filamenthub-plugin",
        "type": "request-slice-reports",
        "bridgeSession": session,
    })

    batch = page.posted_messages[-1]
    assert batch["type"] == "slice-report-batch"
    assert batch["slices"] == [{
        "file_name": "cube.gcode",
        "source_key": source_key,
        "source_instance_id": "source-instance-1234",
    }]

    page.on_message({
        "source": "filamenthub-plugin",
        "type": "slice-report-result",
        "bridgeSession": session,
        "requestId": batch["requestId"],
        "sourceKeys": [source_key],
        "ok": False,
    })
    assert len(module._load_slice_report_outbox()) == 1

    page.on_message({
        "source": "filamenthub-plugin",
        "type": "slice-report-result",
        "bridgeSession": session,
        "requestId": batch["requestId"],
        "sourceKeys": [source_key],
        "ok": True,
    })
    assert module._load_slice_report_outbox() == []


def test_page_acknowledgement_continues_with_the_next_slice_batch(
    tmp_path, monkeypatch
):
    module, _ = _module_with_pages()
    _slice_storage(module, tmp_path, monkeypatch)
    for index in range(26):
        module._queue_slice_report({
            "file_name": "slice-%d.gcode" % index,
            "source_key": "%064x" % index,
            "source_instance_id": "source-instance-1234",
        })
    page = module.FilamentHubPage()
    page.get_ui()
    session = page._catalog._direct_bridge_session
    page.on_message({
        "source": "filamenthub-plugin",
        "type": "request-slice-reports",
        "bridgeSession": session,
    })
    first = page.posted_messages[-1]
    assert len(first["slices"]) == 25

    page.on_message({
        "source": "filamenthub-plugin",
        "type": "slice-report-result",
        "bridgeSession": session,
        "requestId": first["requestId"],
        "sourceKeys": [item["source_key"] for item in first["slices"]],
        "ok": True,
    })

    second = page.posted_messages[-1]
    assert second["type"] == "slice-report-batch"
    assert [item["file_name"] for item in second["slices"]] == ["slice-25.gcode"]


def test_plugin_settings_switch_the_server_at_load_but_keep_one_account_origin(monkeypatch):
    module, _ = _module_with_pages(native_lifecycle=True)
    monkeypatch.delenv("FILAMENTHUB_SITE_URL", raising=False)
    monkeypatch.setattr(module, "SITE_URL", module.PROD_SITE_URL)
    monkeypatch.setattr(module, "DEV_CONTOUR", False)
    monkeypatch.setattr(module, "configure_plugin_storage", lambda: None)
    monkeypatch.setattr(module, "start_plugin_runtime", lambda **_kwargs: None)
    page = module.FilamentHubPage()
    page.get_config = lambda: json.dumps({"server": "club", "developer_mode": "yes"})

    page.on_load()

    assert module.API_BASE == "https://filamenthub.club/api/v1"
    assert module.EMBED_URL == "https://filamenthub.club/embed/catalog"
    assert module.account_origin() == module.PROD_SITE_URL
    assert module.plugin_setting("developer_mode") is False
    settings_page = page.get_config_ui()
    assert "__" not in settings_page
    assert '"club"' in settings_page
    assert module.ui_text("settingsDeveloperModeHint") in settings_page


def test_plugin_settings_gate_automatic_sync_and_the_problem_log(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    session = page._catalog._direct_bridge_session
    config = {"auto_sync": False, "developer_mode": False}
    page.get_config = lambda: json.dumps(config)
    started, submitted = [], []
    monkeypatch.setattr(module, "save_auth", lambda _token: True)
    monkeypatch.setattr(module.BAMBU_BRIDGE_RUNTIME, "wake", lambda: None)
    monkeypatch.setattr(
        module, "BACKGROUND_WORKER", SimpleNamespace(submit=lambda job, *_args: submitted.append(job))
    )
    page._catalog._auto_sync = lambda **kwargs: started.append(kwargs["trigger"]) or True

    def send(message_type, **extra):
        page.on_message(json.dumps({
            "source": "filamenthub-plugin",
            "type": message_type,
            "bridgeSession": session,
            **extra,
        }))

    send("auth-token", accessToken="first-token")
    send("profile-changed")
    send("read-diagnostics")
    send("plugin-capabilities-request")
    assert started == []
    assert submitted == []
    assert page.posted_messages[-1]["developerMode"] is False

    config.update(auto_sync=True, developer_mode=True)
    send("auth-token", accessToken="first-token")
    send("read-diagnostics")
    assert started == ["session-auth"]
    assert len(submitted) == 1


def test_pages_host_opens_https_without_creating_a_loopback_socket(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()

    html = page.get_ui()

    assert module.EMBED_URL in html
    assert "fh_bridge=" in html
    assert page._catalog._direct_bridge_session not in html.split("fh_bridge=", 1)[0]
    assert "127.0.0.1" not in html
    assert "fetch(target" in html
    assert module.ui_text("unavailableTitle") in html
    assert module.ui_text("retry") in html


def test_pages_host_opens_a_separately_bound_local_credential_dialog(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    created = []

    class LocalWindow:
        def __init__(self):
            self.closed = False
            self.messages = []

        def is_open(self):
            return not self.closed

        def post(self, payload):
            self.messages.append(payload)

        def close(self):
            self.closed = True

    def create_window(**kwargs):
        window = LocalWindow()
        created.append((kwargs, window))
        return window

    module.orca.host.ui.create_window = create_window
    action = {
        "source": "filamenthub-plugin",
        "type": "configure-bambu",
        "bridgeSession": page._catalog._direct_bridge_session,
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "pairingCode": "single-use-code",
    }

    page.on_message(json.dumps(action))

    assert len(created) == 1
    options, _window = created[0]
    assert options["title"] == "FilamentHub"
    assert "localDialogSession" in options["html"]
    assert "127.0.0.1" not in options["html"]
    assert page._catalog._direct_bridge_session not in options["html"]
    assert page.posted_messages == [{
        "source": "filamenthub-host",
        "type": "local-printer-setup-state",
        "provider": "bambu",
        "open": True,
        "physicalPrinterId": 11,
        "materialSystemId": 21,
    }]

def test_pages_host_rejects_unbound_and_secret_bearing_remote_commands(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    submitted = []
    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=lambda *args: submitted.append(args)),
    )

    page.on_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "read-diagnostics",
        "bridgeSession": "wrong-session-token-1234567890",
    }))
    page.on_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "configure-bambu-local",
        "bridgeSession": page._catalog._direct_bridge_session,
        "host": "192.0.2.10",
        "accessCode": "local-secret",
    }))

    assert submitted == []
    assert page.posted_messages == []


def test_pages_host_runs_material_commands_sent_with_the_tab_binding(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    submitted = []
    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=lambda job, *_args: submitted.append(job.__name__)),
    )
    monkeypatch.setattr(module, "observe_printer_presets", lambda: [])
    monkeypatch.setattr(module, "observe_local_moonraker_connections", lambda _observations: [])

    for index, message_type in enumerate(
        ("bambu-material-refresh", "happy-hare-material-refresh")
    ):
        page.on_message(json.dumps({
            "source": "filamenthub-plugin",
            "type": message_type,
            "bridgeSession": page._catalog._direct_bridge_session,
            "requestId": "material-check-%d" % index,
            "physicalPrinterId": 11,
            "materialSystemId": 21,
        }))

    assert submitted == [
        "_do_bambu_material_immediate",
        "_do_happy_hare_material_immediate",
    ]


def test_problem_report_log_carries_no_secrets_or_terminal_controls(
    plugin_module, monkeypatch, tmp_path
):
    log = tmp_path / ".fh_sync.log"
    log.write_text(
        "\n".join([
            "2026-09-18 09:55:21 Authorization: Bearer abc.def.ghi",
            "2026-09-18 09:55:22 bridge fhpb_secretvalue123 access_code=12345678",
            "2026-09-18 09:55:22 token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.c2lnbmF0dXJl",
            "2026-09-18 09:55:23 \x1b[31mred\x1b[0m ‮evil",
        ]) + "\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(plugin_module, "SYNC_LOG_FILE", str(log))

    report = plugin_module.diagnostic_report_text()

    assert report.startswith("FilamentHub plugin %s\n" % plugin_module.PLUGIN_VERSION)
    for leaked in ("abc.def.ghi", "secretvalue123", "12345678", "eyJhbGci", "\x1b", "‮"):
        assert leaked not in report
    assert "[31mred[0m evil" in report

    log.write_text("oldest line\n" + "line\n" * 20000, encoding="utf-8")
    bounded = plugin_module.diagnostic_report_text()

    assert len(bounded.encode("utf-8")) <= plugin_module.DIAGNOSTIC_REPORT_MAX_BYTES
    assert "oldest line" not in bounded
    assert bounded.endswith("line\n")


def test_local_credential_submission_requires_the_separate_dialog_binding(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    submitted = []

    class LocalWindow:
        def is_open(self):
            return True

        def post(self, _payload):
            return None

        def close(self):
            return None

    module.orca.host.ui.create_window = lambda **_kwargs: LocalWindow()
    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=lambda *args: submitted.append(args)),
    )
    monkeypatch.setattr(module, "observe_printer_presets", lambda: [])
    monkeypatch.setattr(module, "load_saved_auth", lambda: {"accessToken": "token"})

    page.on_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "configure-bambu",
        "bridgeSession": page._catalog._direct_bridge_session,
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "pairingCode": "single-use-code",
    }))
    local_session = page._catalog._local_dialog_session

    payload = {
        "source": "filamenthub-plugin",
        "type": "prepare-bambu-local",
        "requestId": "search-1",
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "pairingCode": "single-use-code",
    }
    page.on_message(json.dumps(dict(payload, localDialogSession="wrong-binding-token")))
    assert submitted == []

    page.on_message(json.dumps(dict(payload, localDialogSession=local_session)))
    assert len(submitted) == 1
    assert submitted[0][0] == page._catalog._do_prepare_bambu


def test_local_bambu_config_reports_unavailable_worker(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    windows = []

    class LocalWindow:
        def __init__(self):
            self.messages = []

        def is_open(self):
            return True

        def post(self, payload):
            self.messages.append(payload)

        def close(self):
            return None

    def create_window(**_kwargs):
        window = LocalWindow()
        windows.append(window)
        return window

    module.orca.host.ui.create_window = create_window
    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=lambda *args: False),
    )

    page.on_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "configure-bambu",
        "bridgeSession": page._catalog._direct_bridge_session,
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "pairingCode": "single-use-code",
    }))
    local_session = page._catalog._local_dialog_session
    page.on_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "configure-bambu-local",
        "localDialogSession": local_session,
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "host": "192.168.1.42",
        "accessCode": "local-secret",
        "serial": "SERIAL-42",
        "pairingCode": "single-use-code",
        "requestId": "connect-1",
    }))

    assert windows[-1].messages[-1] == {
        "source": "filamenthub-host",
        "type": "bambu-setup-result",
        "requestId": "connect-1",
        "ok": False,
        "code": "bambuSetupUnavailable",
    }


def test_local_bambu_search_does_not_require_pairing_code(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    submitted = []
    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=lambda *args: submitted.append(args) or True),
    )
    catalog = page._catalog
    catalog._local_dialog_session = "local-session"
    catalog._local_window = SimpleNamespace(is_open=lambda: True, post=lambda _payload: None)

    catalog._on_local_dialog_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "prepare-bambu-local",
        "requestId": "search-without-pairing-code",
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "refresh": True,
    }))

    assert len(submitted) == 1
    assert submitted[0][0] == catalog._do_prepare_bambu
    assert submitted[0][1]["refresh"] is True
    assert submitted[0][1]["pairingCode"] == ""


def test_local_bambu_connect_reports_missing_pairing_code(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    messages = []

    def fail_submit(*_args):
        raise AssertionError("pairing must be rejected before worker")

    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=fail_submit),
    )
    catalog = page._catalog
    catalog._local_dialog_session = "local-session"
    catalog._local_window = SimpleNamespace(
        is_open=lambda: True,
        post=lambda payload: messages.append(payload),
    )

    catalog._on_local_dialog_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "configure-bambu-local",
        "requestId": "connect-without-pairing-code",
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "host": "192.168.1.42",
        "accessCode": "local-secret",
        "serial": "SERIAL-42",
    }))

    assert messages[-1] == {
        "source": "filamenthub-host",
        "type": "bambu-setup-result",
        "requestId": "connect-without-pairing-code",
        "ok": False,
        "code": "bambuPairingFailed",
    }


_WINDOW_OWN_PROPERTIES = frozenset({
    "closed", "customElements", "document", "external", "frames", "history",
    "length", "location", "locationbar", "menubar", "name", "navigator",
    "opener", "origin", "parent", "personalbar", "screen", "scrollbars",
    "self", "status", "statusbar", "toolbar", "top",
})


def test_local_dialog_script_does_not_name_a_window_property():
    module, _ = _module_with_pages()
    script = module.LOCAL_DIALOG_PAGE.split("<script>")[1].split("</script>")[0]
    declared = set()
    for chunk in re.findall(r"(?:^|[\s;])var\s+(.+?);", script, re.S):
        for part in chunk.split(","):
            name = part.split("=")[0].strip()
            if re.fullmatch(r"[A-Za-z_$][\w$]*", name):
                declared.add(name)

    assert declared
    assert not declared & _WINDOW_OWN_PROPERTIES


def test_catalog_accepts_string_messages_from_older_host_windows(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    submitted = []
    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=lambda *args: submitted.append(args) or True),
    )

    catalog = page._catalog
    catalog._local_dialog_session = "local-session"
    catalog._local_window = SimpleNamespace(is_open=lambda: True, post=lambda _payload: None)
    catalog.on_message(json.dumps({
        "source": "filamenthub-plugin",
        "localDialogSession": "local-session",
        "type": "prepare-bambu-local",
        "requestId": "search-1",
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "pairingCode": "single-use-code",
    }))

    assert len(submitted) == 1
    assert submitted[0][0] == catalog._do_prepare_bambu


def test_local_dialog_callback_binds_messages_to_its_window(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    submitted = []
    monkeypatch.setattr(
        module,
        "BACKGROUND_WORKER",
        SimpleNamespace(submit=lambda *args: submitted.append(args) or True),
    )

    catalog = page._catalog
    catalog._local_dialog_session = "local-session"
    catalog._local_window = SimpleNamespace(is_open=lambda: True, post=lambda _payload: None)
    catalog._on_local_dialog_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "prepare-bambu-local",
        "requestId": "search-1",
        "physicalPrinterId": 11,
        "materialSystemId": 21,
        "pairingCode": "single-use-code",
    }))

    assert len(submitted) == 1
    assert submitted[0][0] == catalog._do_prepare_bambu


def test_external_oauth_opens_only_the_bound_filamenthub_flow(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    opened = []
    monkeypatch.setattr(module, "open_in_system_browser", lambda url: opened.append(url) or True)

    common = {
        "source": "filamenthub-plugin",
        "type": "open-oauth",
        "provider": "yandex",
        "requestId": "oauth-request-1",
        "bridgeSession": page._catalog._direct_bridge_session,
    }
    page.on_message(json.dumps(dict(common, path="https://evil.example/steal")))
    page.on_message(json.dumps(dict(common, path="/oauth/plugin-start/yandex?flow=short")))
    assert opened == []

    flow = "a" * 32
    page.on_message(json.dumps(dict(common, path=f"/oauth/plugin-start/yandex?flow={flow}")))
    assert opened == [f"{module.SITE_URL}/oauth/plugin-start/yandex?flow={flow}"]
    assert page.posted_messages[-1] == {
        "source": "filamenthub-host",
        "type": "oauth-browser-opened",
        "opened": True,
        "requestId": "oauth-request-1",
    }


def test_pages_host_answers_capabilities_on_the_bound_direct_bridge(monkeypatch):
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()
    page.get_ui()
    monkeypatch.setattr(page._catalog, "_auto_sync", lambda **_kwargs: False)

    page.on_message(json.dumps({
        "source": "filamenthub-plugin",
        "type": "plugin-capabilities-request",
        "bridgeSession": page._catalog._direct_bridge_session,
    }))

    assert page.posted_messages == [{
        "source": "filamenthub-host",
        "type": "plugin-capabilities",
        "pluginVersion": module.PLUGIN_VERSION,
        "capabilities": list(module.PLUGIN_CAPABILITIES),
        "developerMode": False,
    }]

def test_page_icon_materializes_for_a_single_file_install(
    plugin_module, tmp_path, monkeypatch
):
    missing = tmp_path / "not-packaged.svg"
    monkeypatch.setattr(plugin_module, "PACKAGED_ICON_PATH", str(missing))
    monkeypatch.setattr(plugin_module, "ICON_PATH", str(missing))
    monkeypatch.setattr(plugin_module, "PLUGIN_STORAGE_DIR", str(tmp_path))
    icon = plugin_module.ensure_icon()
    assert icon == str(tmp_path / "filamenthub.svg")
    assert (tmp_path / "filamenthub.svg").read_bytes() == plugin_module._ICON_SVG

def test_host_storage_migrates_mutable_state_without_deleting_legacy(
    plugin_module, tmp_path, monkeypatch
):
    legacy = tmp_path / "plugin"
    storage = tmp_path / "plugin_data" / "filamenthub"
    legacy.mkdir()
    (legacy / ".auth.json").write_text('{"accessToken":"fixture"}', encoding="utf-8")
    (legacy / ".fh_bambu.json").write_text(
        '{"version":1,"source_instance_id":"fixture-instance-0001","printers":[]}',
        encoding="utf-8",
    )
    (legacy / ".fh_bambu_revoke.json").write_text(
        '{"version":1,"pending":[]}', encoding="utf-8"
    )
    (legacy / ".fh_sync.json").write_text('{"known":true}', encoding="utf-8")
    (legacy / "slices").mkdir()
    (legacy / "slices" / "fixture.gcode").write_text("G28", encoding="utf-8")

    monkeypatch.setattr(plugin_module, "PLUGIN_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "PLUGIN_STORAGE_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "SYNC_LOG_FILE", str(legacy / ".fh_sync.log"))
    monkeypatch.setattr(plugin_module, "AUTH_FILE", str(legacy / ".auth.json"))
    monkeypatch.setattr(plugin_module, "BAMBU_CONFIG_FILE", str(legacy / ".fh_bambu.json"))
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_FILE",
        str(legacy / ".fh_bambu_revoke.json"),
    )
    monkeypatch.setattr(
        plugin_module,
        "PRINTER_BUNDLE_STATE_FILE",
        str(legacy / ".fh_printer_bundles.json"),
    )
    monkeypatch.setattr(
        plugin_module, "IMPORTED_DRAFTS_FILE", str(legacy / ".fh_imported.json")
    )
    monkeypatch.setattr(plugin_module, "SYNC_STATE_FILE", str(legacy / ".fh_sync.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_INDEX_FILE", str(legacy / ".fh_slices.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_CACHE_DIR", str(legacy / "slices"))
    monkeypatch.setattr(
        plugin_module.orca.host,
        "plugin",
        SimpleNamespace(storage=lambda: str(storage)),
        raising=False,
    )

    plugin_module.stop_plugin_runtime()
    plugin_module.FilamentHubPlugin().register_capabilities()

    assert plugin_module.PLUGIN_STORAGE_DIR == str(storage)
    assert plugin_module.AUTH_FILE == str(storage / ".auth.json")
    assert plugin_module.BAMBU_CONFIG_FILE == str(storage / ".fh_bambu.json")
    assert plugin_module.BAMBU_REVOKE_FILE == str(
        storage / ".fh_bambu_revoke.json"
    )
    assert plugin_module.PRINTER_BUNDLE_STATE_FILE == str(
        storage / ".fh_printer_bundles.json"
    )
    assert plugin_module.SYNC_STATE_FILE == str(storage / ".fh_sync.json")
    assert plugin_module._SLICE_CACHE_DIR == str(storage / "slices")
    assert (storage / ".auth.json").read_text(encoding="utf-8") == (
        '{"accessToken":"fixture"}'
    )
    assert (storage / ".fh_bambu.json").exists()
    assert (storage / ".fh_bambu_revoke.json").exists()
    assert (storage / "slices" / "fixture.gcode").read_text(encoding="utf-8") == "G28"
    assert (legacy / ".auth.json").exists()
    assert (legacy / ".fh_bambu_revoke.json").exists()
    assert (legacy / "slices" / "fixture.gcode").exists()

def test_host_without_storage_uses_data_root_outside_replaceable_plugin_dir(
    plugin_module, tmp_path, monkeypatch
):
    data_root = tmp_path / "orca-data"
    legacy = data_root / "orca_plugins" / "filamenthub_plugin.py"
    stable = data_root / ".filamenthub" / "orca-plugin"
    legacy.mkdir(parents=True)
    (legacy / ".auth.json").write_text('{"accessToken":"fixture"}', encoding="utf-8")
    (legacy / ".fh_bambu.json").write_text(
        '{"version":1,"source_instance_id":"fixture-instance-0001","printers":[]}',
        encoding="utf-8",
    )

    monkeypatch.setattr(plugin_module, "PLUGIN_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "PLUGIN_STORAGE_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "SYNC_LOG_FILE", str(legacy / ".fh_sync.log"))
    monkeypatch.setattr(plugin_module, "AUTH_FILE", str(legacy / ".auth.json"))
    monkeypatch.setattr(plugin_module, "BAMBU_CONFIG_FILE", str(legacy / ".fh_bambu.json"))
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_FILE",
        str(legacy / ".fh_bambu_revoke.json"),
    )
    monkeypatch.setattr(
        plugin_module,
        "PRINTER_BUNDLE_STATE_FILE",
        str(legacy / ".fh_printer_bundles.json"),
    )
    monkeypatch.setattr(
        plugin_module, "IMPORTED_DRAFTS_FILE", str(legacy / ".fh_imported.json")
    )
    monkeypatch.setattr(plugin_module, "SYNC_STATE_FILE", str(legacy / ".fh_sync.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_INDEX_FILE", str(legacy / ".fh_slices.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_CACHE_DIR", str(legacy / "slices"))
    monkeypatch.setattr(
        plugin_module.orca.host,
        "plugin",
        SimpleNamespace(),
        raising=False,
    )

    assert plugin_module.configure_plugin_storage() is True

    assert plugin_module.PLUGIN_STORAGE_DIR == str(stable)
    assert plugin_module.AUTH_FILE == str(stable / ".auth.json")
    assert plugin_module.BAMBU_CONFIG_FILE == str(stable / ".fh_bambu.json")
    assert plugin_module.BAMBU_REVOKE_FILE == str(
        stable / ".fh_bambu_revoke.json"
    )
    assert plugin_module.PRINTER_BUNDLE_STATE_FILE == str(
        stable / ".fh_printer_bundles.json"
    )
    assert (stable / ".auth.json").read_text(encoding="utf-8") == (
        '{"accessToken":"fixture"}'
    )
    assert (stable / ".fh_bambu.json").exists()
    assert (legacy / ".auth.json").exists()
