"""Slicing, host storage and runtime resource contracts."""

from .filamenthub_plugin_test_support import (
    json,
    _module_with_pages,
    _module_with_slicing,
    SimpleNamespace,
    _slice_storage,
)


def test_a_slice_is_identified_by_the_machine_it_was_made_for(tmp_path):
    """Only what names the slice travels; figures come from reading the file."""
    module, _ = _module_with_slicing()
    gcode = tmp_path / "Cube_PETG.gcode"
    gcode.write_text(
        chr(10).join(
            [
                "; generated by OrcaSlicer 2.4.2 on 2026-07-11 at 10:39:05",
                "G1 X1 Y1 E1",
                "; total filament used [g] = 151.22",
                '; printer_settings_id = "Voron 2.4 350 0.4 nozzle"',
                '; printer_model = "Voron 2.4 350"',
            ]
        ),
        encoding="utf-8",
    )

    identity = module._read_slice_identity(str(gcode))

    assert identity["printer_settings_id"] == "Voron 2.4 350 0.4 nozzle"
    assert identity["printer_model"] == "Voron 2.4 350"
    assert identity["slicer_version"] == "2.4.2"
    # Weights stay out of it: the file is the one source of them.
    assert not any("weight" in key or "seconds" in key for key in identity)

def test_managed_profile_identities_are_written_per_kind_and_tool_once(
    tmp_path, monkeypatch
):
    """One numeric id may exist in three tables; kind and tool keep it exact."""
    module, _ = _module_with_slicing()
    monkeypatch.setattr(module, "DATA_DIR", str(tmp_path))
    monkeypatch.setattr(module, "_user_preset_folder", "default")

    managed = {
        "filament": ("Material", 7),
        "process": ("Process", 7),
        "machine": ("Machine", 7),
    }
    for folder, (name, entity_id) in managed.items():
        target = tmp_path / "user" / "default" / "_local" / "filamenthub" / folder
        target.mkdir(parents=True, exist_ok=True)
        (target / (name + ".json")).write_text(
            json.dumps({"name": name, "bundle_id": "filamenthub:%d" % entity_id}),
            encoding="utf-8",
        )

    config = {
        "filament_settings_id": '"_local/filamenthub/Material";"Generic PETG @System"',
        "print_settings_id": "_local/filamenthub/Process",
        "printer_settings_id": "_local/filamenthub/Machine",
    }
    ctx = SimpleNamespace(config_value=lambda key: config.get(key))
    identities = module._slice_managed_identities(ctx)
    gcode = tmp_path / "managed.gcode"
    gcode.write_text(
        chr(10).join(
            [
                "; generated by OrcaSlicer 2.5.0-dev",
                "; print_settings_id = Process",
                "; printer_settings_id = Machine",
            ]
        ),
        encoding="utf-8",
    )

    assert identities == [
        {"kind": "material_preset", "tool_index": 0, "id": 7},
        {"kind": "print_profile", "tool_index": None, "id": 7},
        {"kind": "printer_profile", "tool_index": None, "id": 7},
    ]
    assert module._append_fhub_slice_identities(str(gcode), identities)
    assert module._append_fhub_slice_identities(str(gcode), identities)

    content = gcode.read_text(encoding="utf-8")
    assert content.count("fhub_identity_v1") == 3
    assert "kind=material_preset;tool=0;id=7" in content
    reported = module._read_slice_identity(str(gcode))
    assert reported["fhub_print_profile_id"] == 7
    assert reported["fhub_printer_profile_id"] == 7

def test_the_path_stays_behind_a_key_the_site_can_ask_with(tmp_path, monkeypatch):
    """A path carries a person's folders, so only a key leaves this machine."""
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    gcode = tmp_path / "Cube_PETG.gcode"
    gcode.write_text("; generated by OrcaSlicer 2.4.2", encoding="utf-8")

    key = module._remember_slice_path(str(gcode))

    assert key and str(gcode) not in key
    assert module.slice_path_for_key(key) == str(gcode)
    assert module.slice_path_for_key("nothing-like-it") is None

    gcode.unlink()
    assert module.slice_path_for_key(key) is None

def test_a_slice_sent_to_a_printer_survives_the_host_deleting_it(tmp_path, monkeypatch):
    """Uploading writes a temp file the host removes; a copy keeps it countable."""
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)
    upload = tmp_path / ".OrcaSlicer.upload.5ca1-0810"
    upload.write_text("; generated by OrcaSlicer 2.4.2", encoding="utf-8")

    key = module._remember_slice_path(str(upload), "Cube_PETG.gcode")
    upload.unlink()

    entry = module.slice_entry_for_key(key)
    assert entry is not None and entry["path"] != str(upload)
    # The copy is named after the key, so the name a person gave the print is
    # what the calculation must be labelled with.
    assert entry["name"] == "Cube_PETG.gcode"
    with open(entry["path"], "r", encoding="utf-8") as fh:
        assert fh.read() == "; generated by OrcaSlicer 2.4.2"

def test_only_the_newest_few_uploads_are_kept(tmp_path, monkeypatch):
    """The cache is a convenience, not an archive of someone's disk."""
    module, _ = _module_with_slicing()
    _slice_storage(module, tmp_path, monkeypatch)

    keys = []
    for number in range(module._SLICE_CACHE_FILES + 3):
        upload = tmp_path / (".OrcaSlicer.upload.%d" % number)
        upload.write_text("; slice %d" % number, encoding="utf-8")
        keys.append(module._remember_slice_path(str(upload)))
        upload.unlink()

    kept = [key for key in keys if module.slice_path_for_key(key)]
    assert len(kept) == module._SLICE_CACHE_FILES
    assert keys[-1] in kept

def test_the_reporter_is_registered_only_where_the_host_can_slice():
    """A host without the slicing pipeline must still load the plugin."""
    with_slicing, registered = _module_with_slicing()
    assert with_slicing.FilamentHubSliceReporter is not None
    with_slicing.FilamentHubPlugin().register_capabilities()
    assert with_slicing.FilamentHubSliceReporter in registered

def test_without_the_pipeline_the_plugin_still_registers_its_window(plugin_module):
    assert plugin_module.FilamentHubSliceReporter is None
    plugin_module.FilamentHubPlugin().register_capabilities()

def test_pages_host_registers_a_tab_instead_of_the_window_action():
    module, registered = _module_with_pages()
    module.FilamentHubPlugin().register_capabilities()
    assert module.FilamentHubPage in registered
    assert module.FilamentHubCatalog not in registered

def test_current_host_defers_runtime_resources_to_capability_lifecycle(monkeypatch):
    module, _ = _module_with_pages(native_lifecycle=True)
    lifecycle = []
    stopped = []
    monkeypatch.setattr(
        module,
        "configure_plugin_storage",
        lambda: lifecycle.append("storage") or True,
    )
    monkeypatch.setattr(
        module,
        "start_plugin_runtime",
        lambda storage_initialized=False: lifecycle.append(
            ("start", storage_initialized)
        ),
    )
    monkeypatch.setattr(module, "stop_plugin_runtime", lambda: stopped.append(True))

    module.FilamentHubPlugin().register_capabilities()
    assert lifecycle == []

    page = module.FilamentHubPage()
    page.on_load()
    page.on_cancelled()
    page.on_unload()

    assert lifecycle == ["storage", ("start", True)]
    assert stopped == [True, True]

def test_old_host_keeps_registration_time_runtime_fallback(monkeypatch):
    module, _ = _module_with_pages(native_lifecycle=False)
    started = []
    monkeypatch.setattr(module, "start_plugin_runtime", lambda: started.append(True))

    module.FilamentHubPlugin().register_capabilities()

    assert started == [True]

def test_runtime_stop_closes_every_owned_resource(plugin_module, monkeypatch):
    stopped = []
    monkeypatch.setattr(
        plugin_module,
        "BACKGROUND_WORKER",
        SimpleNamespace(stop=lambda: stopped.append("worker")),
    )
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_BRIDGE_RUNTIME",
        SimpleNamespace(stop=lambda: stopped.append("bambu")),
    )
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_SCHEDULER",
        SimpleNamespace(stop=lambda: stopped.append("revoke-scheduler")),
    )
    monkeypatch.setattr(
        plugin_module,
        "SHELL_SERVER",
        SimpleNamespace(stop=lambda: stopped.append("loopback")),
    )
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_ACTIVE", True)
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_EPOCH", 1)

    assert plugin_module.stop_plugin_runtime() is True
    assert stopped == ["revoke-scheduler", "worker", "bambu", "loopback"]
    assert plugin_module._PLUGIN_RUNTIME_ACTIVE is False

def test_runtime_load_starts_pending_bambu_revoke_scheduler(
    plugin_module, monkeypatch
):
    calls = []

    class Worker:
        def activate(self):
            calls.append("activate")

        def stop(self):
            calls.append("stop")

    monkeypatch.setattr(plugin_module, "BACKGROUND_WORKER", Worker())
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_BRIDGE_RUNTIME",
        SimpleNamespace(start=lambda: calls.append("bambu-start"), stop=lambda: None),
    )
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_SCHEDULER",
        SimpleNamespace(
            start=lambda: calls.append("revoke-start"),
            stop=lambda: calls.append("revoke-stop"),
        ),
    )
    monkeypatch.setattr(plugin_module, "SHELL_SERVER", SimpleNamespace(stop=lambda: None))
    monkeypatch.setattr(plugin_module, "refresh_ui_language", lambda: None)
    monkeypatch.setattr(
        plugin_module,
        "load_bambu_config",
        lambda: {"source_instance_id": "fixture", "printers": []},
    )
    monkeypatch.setattr(plugin_module, "repair_local_bundle_parents", lambda: 0)
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_ACTIVE", False)
    monkeypatch.setattr(plugin_module, "_PLUGIN_RUNTIME_EPOCH", 0)

    assert plugin_module.start_plugin_runtime(storage_initialized=True) is True
    assert calls[:2] == ["activate", "revoke-start"]
    assert plugin_module.stop_plugin_runtime() is True

def test_pages_host_delivers_plugin_messages_through_post_message():
    module, _ = _module_with_pages()
    page = module.FilamentHubPage()

    page._catalog._deliver_sync_result("Synced", 2)

    assert page.posted_messages == [{
        "source": "filamenthub-host",
        "type": "sync-result",
        "text": "Synced",
        "draftCount": 2,
        "operationId": "",
        "scope": "all",
        "status": "success",
        "contours": [],
    }]

def test_notice_uses_typed_loopback_fallback_without_a_push_transport(
    plugin_module, monkeypatch
):
    captured = []
    monkeypatch.setattr(
        plugin_module.SHELL_SERVER,
        "set_sync_result",
        lambda payload: captured.append(payload),
    )

    plugin_module.FilamentHubCatalog()._deliver_notice("Saved", "success")

    assert captured == [{
        "text": "Saved",
        "status": "success",
        "resultType": "plugin-notice",
    }]

def test_page_icon_materializes_for_a_single_file_install(
    plugin_module, tmp_path, monkeypatch
):
    missing = tmp_path / "not-packaged.svg"
    monkeypatch.setattr(plugin_module, "PACKAGED_ICON_PATH", str(missing))
    monkeypatch.setattr(plugin_module, "ICON_PATH", str(missing))
    monkeypatch.setattr(plugin_module, "PLUGIN_STORAGE_DIR", str(tmp_path))
    icon = plugin_module.ensure_icon()
    assert icon == str(tmp_path / "filamenthub.svg")
    assert (tmp_path / "filamenthub.svg").read_bytes() == plugin_module._ICON_SVG

def test_host_storage_migrates_mutable_state_without_deleting_legacy(
    plugin_module, tmp_path, monkeypatch
):
    legacy = tmp_path / "plugin"
    storage = tmp_path / "plugin_data" / "filamenthub"
    legacy.mkdir()
    (legacy / ".auth.json").write_text('{"accessToken":"fixture"}', encoding="utf-8")
    (legacy / ".fh_bambu.json").write_text(
        '{"version":1,"source_instance_id":"fixture-instance-0001","printers":[]}',
        encoding="utf-8",
    )
    (legacy / ".fh_bambu_revoke.json").write_text(
        '{"version":1,"pending":[]}', encoding="utf-8"
    )
    (legacy / ".fh_sync.json").write_text('{"known":true}', encoding="utf-8")
    (legacy / "slices").mkdir()
    (legacy / "slices" / "fixture.gcode").write_text("G28", encoding="utf-8")

    monkeypatch.setattr(plugin_module, "PLUGIN_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "PLUGIN_STORAGE_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "SYNC_LOG_FILE", str(legacy / ".fh_sync.log"))
    monkeypatch.setattr(plugin_module, "AUTH_FILE", str(legacy / ".auth.json"))
    monkeypatch.setattr(plugin_module, "BAMBU_CONFIG_FILE", str(legacy / ".fh_bambu.json"))
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_FILE",
        str(legacy / ".fh_bambu_revoke.json"),
    )
    monkeypatch.setattr(
        plugin_module,
        "PRINTER_BUNDLE_STATE_FILE",
        str(legacy / ".fh_printer_bundles.json"),
    )
    monkeypatch.setattr(
        plugin_module, "IMPORTED_DRAFTS_FILE", str(legacy / ".fh_imported.json")
    )
    monkeypatch.setattr(plugin_module, "SYNC_STATE_FILE", str(legacy / ".fh_sync.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_INDEX_FILE", str(legacy / ".fh_slices.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_CACHE_DIR", str(legacy / "slices"))
    monkeypatch.setattr(
        plugin_module.orca.host,
        "plugin",
        SimpleNamespace(storage=lambda: str(storage)),
        raising=False,
    )

    plugin_module.stop_plugin_runtime()
    plugin_module.FilamentHubPlugin().register_capabilities()

    assert plugin_module.PLUGIN_STORAGE_DIR == str(storage)
    assert plugin_module.AUTH_FILE == str(storage / ".auth.json")
    assert plugin_module.BAMBU_CONFIG_FILE == str(storage / ".fh_bambu.json")
    assert plugin_module.BAMBU_REVOKE_FILE == str(
        storage / ".fh_bambu_revoke.json"
    )
    assert plugin_module.PRINTER_BUNDLE_STATE_FILE == str(
        storage / ".fh_printer_bundles.json"
    )
    assert plugin_module.SYNC_STATE_FILE == str(storage / ".fh_sync.json")
    assert plugin_module._SLICE_CACHE_DIR == str(storage / "slices")
    assert (storage / ".auth.json").read_text(encoding="utf-8") == (
        '{"accessToken":"fixture"}'
    )
    assert (storage / ".fh_bambu.json").exists()
    assert (storage / ".fh_bambu_revoke.json").exists()
    assert (storage / "slices" / "fixture.gcode").read_text(encoding="utf-8") == "G28"
    assert (legacy / ".auth.json").exists()
    assert (legacy / ".fh_bambu_revoke.json").exists()
    assert (legacy / "slices" / "fixture.gcode").exists()

def test_host_without_storage_uses_data_root_outside_replaceable_plugin_dir(
    plugin_module, tmp_path, monkeypatch
):
    data_root = tmp_path / "orca-data"
    legacy = data_root / "orca_plugins" / "filamenthub_plugin.py"
    stable = data_root / ".filamenthub" / "orca-plugin"
    legacy.mkdir(parents=True)
    (legacy / ".auth.json").write_text('{"accessToken":"fixture"}', encoding="utf-8")
    (legacy / ".fh_bambu.json").write_text(
        '{"version":1,"source_instance_id":"fixture-instance-0001","printers":[]}',
        encoding="utf-8",
    )

    monkeypatch.setattr(plugin_module, "PLUGIN_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "PLUGIN_STORAGE_DIR", str(legacy))
    monkeypatch.setattr(plugin_module, "SYNC_LOG_FILE", str(legacy / ".fh_sync.log"))
    monkeypatch.setattr(plugin_module, "AUTH_FILE", str(legacy / ".auth.json"))
    monkeypatch.setattr(plugin_module, "BAMBU_CONFIG_FILE", str(legacy / ".fh_bambu.json"))
    monkeypatch.setattr(
        plugin_module,
        "BAMBU_REVOKE_FILE",
        str(legacy / ".fh_bambu_revoke.json"),
    )
    monkeypatch.setattr(
        plugin_module,
        "PRINTER_BUNDLE_STATE_FILE",
        str(legacy / ".fh_printer_bundles.json"),
    )
    monkeypatch.setattr(
        plugin_module, "IMPORTED_DRAFTS_FILE", str(legacy / ".fh_imported.json")
    )
    monkeypatch.setattr(plugin_module, "SYNC_STATE_FILE", str(legacy / ".fh_sync.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_INDEX_FILE", str(legacy / ".fh_slices.json"))
    monkeypatch.setattr(plugin_module, "_SLICE_CACHE_DIR", str(legacy / "slices"))
    monkeypatch.setattr(
        plugin_module.orca.host,
        "plugin",
        SimpleNamespace(),
        raising=False,
    )

    assert plugin_module.configure_plugin_storage() is True

    assert plugin_module.PLUGIN_STORAGE_DIR == str(stable)
    assert plugin_module.AUTH_FILE == str(stable / ".auth.json")
    assert plugin_module.BAMBU_CONFIG_FILE == str(stable / ".fh_bambu.json")
    assert plugin_module.BAMBU_REVOKE_FILE == str(
        stable / ".fh_bambu_revoke.json"
    )
    assert plugin_module.PRINTER_BUNDLE_STATE_FILE == str(
        stable / ".fh_printer_bundles.json"
    )
    assert (stable / ".auth.json").read_text(encoding="utf-8") == (
        '{"accessToken":"fixture"}'
    )
    assert (stable / ".fh_bambu.json").exists()
    assert (legacy / ".auth.json").exists()
