"""Contract tests for one-upload Calculator G-code artifacts."""

from __future__ import annotations

import asyncio
import gzip
import io
import os
import threading
import time
import zipfile
from datetime import datetime, timedelta, timezone
from uuid import uuid4

import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.v1.endpoints import calculator as calculator_endpoint
from app.models.calculator_gcode_artifact import CalculatorGcodeArtifact
from app.models.user import User
from app.services import calculator_gcode_artifact_service as artifacts
from app.services import subscription_service
from app.services.calculator_gcode_parser import GcodeParseCancelled, parse_gcode_payload
from app.services.legal_acceptance_service import (
    CURRENT_PERSONAL_DATA_CONSENT_VERSION,
    CURRENT_TERMS_VERSION,
)


def _plain_gcode() -> bytes:
    return (
        "; generated by OrcaSlicer 2.4.0\n"
        "; estimated printing time (normal mode) = 1h 2m\n"
        "; total filament weight [g] : 12.5\n"
        "; filament_type = PLA\n"
        "; filament_settings_id = Generic PLA\n"
    ).encode()


def _multi_plate_3mf() -> bytes:
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("Metadata/plate_1.gcode", _plain_gcode())
        archive.writestr(
            "Metadata/plate_2.gcode",
            _plain_gcode().replace(b"12.5", b"4.5"),
        )
    return output.getvalue()


def _large_plain_gcode(size_bytes: int = 34 * 1024 * 1024) -> bytes:
    header = (
        "; generated by OrcaSlicer 2.4.0\n"
        "; estimated printing time (normal mode) = 6h 24m\n"
        "; total filament weight [g] : 120\n"
        "; filament_type = PETG\n"
        "M83\n"
    ).encode()
    move = b"G1 X1 Y1 E0.001\n"
    body_size = size_bytes - len(header)
    complete_moves, padding_size = divmod(body_size, len(move))
    padding = b"" if padding_size == 0 else b";" + b" " * (padding_size - 2) + b"\n"
    return header + move * complete_moves + padding


@pytest.fixture
def artifact_storage(tmp_path, monkeypatch: pytest.MonkeyPatch):
    root = tmp_path / "calculator-gcode"
    monkeypatch.setattr(artifacts, "artifact_storage_root", lambda: root)
    monkeypatch.setitem(subscription_service._settings_cache, "paywall_enforced", False)
    return root


async def _upload(
    client: AsyncClient,
    payload: bytes,
    *,
    artifact_id: str | None = None,
    file_name: str = "plates.gcode.3mf",
):
    operation_id = artifact_id or str(uuid4())
    response = await client.put(
        f"/api/v1/calculator/gcode-artifacts/{operation_id}",
        params={"file_name": file_name, "expected_size_bytes": len(payload)},
        content=payload,
        headers={"Content-Type": "application/octet-stream"},
    )
    return operation_id, response


@pytest.mark.asyncio
async def test_one_upload_is_reused_for_every_plate_and_retry(
    auth_client: AsyncClient,
    artifact_storage,
) -> None:
    payload = _multi_plate_3mf()
    artifact_id, uploaded = await _upload(auth_client, payload)

    assert uploaded.status_code == 200
    assert uploaded.json()["state"] == "ready"
    assert len(list(artifact_storage.glob("*.bin"))) == 1

    parsed = await auth_client.post(
        f"/api/v1/calculator/gcode-artifacts/{artifact_id}/parse"
    )
    assert parsed.status_code == 200
    assert [job["plate_index"] for job in parsed.json()["jobs"]] == [1, 2]
    assert [job["total_filament_weight_g"] for job in parsed.json()["jobs"]] == [12.5, 4.5]

    # A lost upload response is recovered by the same operation ID. The original
    # immutable blob remains the only stored payload.
    _, retried = await _upload(auth_client, payload, artifact_id=artifact_id)
    assert retried.status_code == 200
    assert retried.json()["sha256"] == uploaded.json()["sha256"]
    assert len(list(artifact_storage.glob("*.bin"))) == 1


@pytest.mark.asyncio
async def test_artifact_is_owner_bound_and_delete_is_idempotent(
    auth_client: AsyncClient,
    client: AsyncClient,
    db_session: AsyncSession,
    artifact_storage,
) -> None:
    payload = _multi_plate_3mf()
    artifact_id, uploaded = await _upload(auth_client, payload)
    assert uploaded.status_code == 200

    other = User(
        email="artifact-other@example.com",
        username="artifactother",
        password_hash="$2b$12$test",
        active=True,
        email_verified=True,
        terms_version_accepted=CURRENT_TERMS_VERSION,
        personal_data_consent_version=CURRENT_PERSONAL_DATA_CONSENT_VERSION,
    )
    db_session.add(other)
    await db_session.commit()
    from app.core.security import create_access_token

    other_client_headers = {"Authorization": f"Bearer {create_access_token({'sub': other.email})}"}
    hidden = await client.get(
        f"/api/v1/calculator/gcode-artifacts/{artifact_id}",
        headers=other_client_headers,
    )
    assert hidden.status_code == 404

    deleted = await auth_client.delete(
        f"/api/v1/calculator/gcode-artifacts/{artifact_id}"
    )
    deleted_again = await auth_client.delete(
        f"/api/v1/calculator/gcode-artifacts/{artifact_id}"
    )
    assert deleted.status_code == deleted_again.status_code == 204
    cancelled = await auth_client.post(
        f"/api/v1/calculator/gcode-artifacts/{artifact_id}/parse"
    )
    assert cancelled.status_code == 409
    assert cancelled.json()["detail"]["code"] == "ERR_GCODE_ARTIFACT_CANCELLED"


@pytest.mark.asyncio
async def test_upload_rejects_truncation_before_publishing_blob(
    auth_client: AsyncClient,
    artifact_storage,
) -> None:
    payload = _plain_gcode()
    artifact_id = str(uuid4())
    response = await auth_client.put(
        f"/api/v1/calculator/gcode-artifacts/{artifact_id}",
        params={"file_name": "job.gcode", "expected_size_bytes": len(payload) + 1},
        content=payload,
    )
    assert response.status_code == 400
    assert response.json()["detail"]["code"] == "ERR_GCODE_UPLOAD_INCOMPLETE"
    assert list(artifact_storage.glob("*.bin")) == []


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("file_name", "payload"),
    [
        ("garbage.gcode", b"this is not machine code"),
        ("empty.gcode", b"\n"),
        ("broken.gcode.gz", gzip.compress(b"G1 X1 E0.1\n")[:-4]),
        ("broken.gcode.3mf", b"PK\x03\x04truncated"),
    ],
)
async def test_artifact_parse_rejects_malformed_content(
    auth_client: AsyncClient,
    artifact_storage,
    file_name: str,
    payload: bytes,
) -> None:
    artifact_id, uploaded = await _upload(auth_client, payload, file_name=file_name)
    assert uploaded.status_code == 200

    parsed = await auth_client.post(f"/api/v1/calculator/gcode-artifacts/{artifact_id}/parse")

    assert parsed.status_code == 400
    assert parsed.json()["detail"]["code"] == "ERR_GCODE_PARSE_FAILED"


@pytest.mark.asyncio
async def test_artifact_upload_rejects_unknown_extension(
    auth_client: AsyncClient,
    artifact_storage,
) -> None:
    _, response = await _upload(
        auth_client,
        b"G1 X1 E0.1\n",
        file_name="unknown.bin",
    )

    assert response.status_code == 400
    assert response.json()["detail"]["code"] == "ERR_INVALID_FILE_EXT"
    assert list(artifact_storage.glob("*.bin")) == []


@pytest.mark.asyncio
async def test_upload_stops_when_cancel_marker_appears(
    db_session: AsyncSession,
    artifact_storage,
    auth_user: User,
) -> None:
    payload = _plain_gcode()
    artifact_id = str(uuid4())
    artifact, needs_upload = await artifacts.reserve_artifact(
        db_session,
        artifact_id=artifact_id,
        owner_user_id=auth_user.id,
        file_name="cancel.gcode",
        expected_size_bytes=len(payload),
    )
    await db_session.commit()
    assert needs_upload

    async def cancelled_chunks():
        midpoint = len(payload) // 2
        yield payload[:midpoint]
        artifacts._cancel_path(artifact_id).touch()
        yield payload[midpoint:]

    with pytest.raises(artifacts.ArtifactCancelledError):
        await artifacts.write_artifact_stream(
            db_session,
            artifact=artifact,
            chunks=cancelled_chunks(),
        )

    assert list(artifact_storage.glob("*.bin")) == []
    assert list(artifact_storage.glob("*.part")) == []


def test_parser_cooperatively_stops_during_a_large_plain_file() -> None:
    payload = ("; generated by OrcaSlicer 2.4.0\n" + "G1 X1 E0.1\n" * 300_000).encode()
    checks = 0

    def cancelled() -> bool:
        nonlocal checks
        checks += 1
        return checks >= 3

    with pytest.raises(GcodeParseCancelled):
        parse_gcode_payload("cancel.gcode", payload, should_cancel=cancelled)


@pytest.mark.asyncio
async def test_artifact_parse_keeps_the_health_route_responsive(
    auth_client: AsyncClient,
    artifact_storage,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    payload = _large_plain_gcode()
    artifact_id, uploaded = await _upload(
        auth_client,
        payload,
        file_name="regression-34mib.gcode",
    )
    assert uploaded.status_code == 200

    worker_started = threading.Event()
    worker_finished = threading.Event()
    original_parse = calculator_endpoint.parse_artifact_payload

    def measured_parse(artifact):
        worker_started.set()
        try:
            return original_parse(artifact)
        finally:
            worker_finished.set()

    monkeypatch.setattr(calculator_endpoint, "parse_artifact_payload", measured_parse)

    task = asyncio.create_task(
        auth_client.post(f"/api/v1/calculator/gcode-artifacts/{artifact_id}/parse")
    )
    assert await asyncio.to_thread(worker_started.wait, 1)

    health_started = time.perf_counter()
    health = await asyncio.wait_for(auth_client.get("/health"), timeout=1)
    health_latency = time.perf_counter() - health_started
    assert health.status_code == 200
    assert health_latency < 1
    assert not worker_finished.is_set()

    parsed = await task
    assert parsed.status_code == 200
    assert len(parsed.json()["jobs"]) == 1


def test_duplicate_plate_names_are_rejected() -> None:
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", _plain_gcode())
        archive.writestr("Metadata/plate_1.gcode", _plain_gcode())
    with pytest.raises(ValueError, match="duplicate_plate"):
        parse_gcode_payload("duplicate.gcode.3mf", output.getvalue())


@pytest.mark.asyncio
async def test_cleanup_removes_expired_rows_and_old_orphan_files(
    db_session: AsyncSession,
    artifact_storage,
    auth_user: User,
) -> None:
    now = datetime.now(timezone.utc)
    artifact_storage.mkdir(parents=True)
    expired_blob = artifact_storage / f"{uuid4()}.bin"
    expired_blob.write_bytes(_plain_gcode())
    artifact = CalculatorGcodeArtifact(
        id=expired_blob.stem,
        owner_user_id=auth_user.id,
        original_name="expired.gcode",
        expected_size_bytes=expired_blob.stat().st_size,
        size_bytes=expired_blob.stat().st_size,
        sha256="0" * 64,
        storage_key=expired_blob.name,
        state="ready",
        expires_at=now - timedelta(seconds=1),
    )
    db_session.add(artifact)
    await db_session.commit()

    orphan = artifact_storage / f"{uuid4()}.1.part"
    orphan.write_bytes(b"partial")
    old_timestamp = (now - artifacts.ORPHAN_FILE_GRACE - timedelta(seconds=1)).timestamp()
    orphan.touch()
    os.utime(orphan, (old_timestamp, old_timestamp))

    removed = await artifacts.cleanup_expired_artifacts(db_session, now=now)
    await db_session.commit()

    assert removed == 1
    assert await db_session.get(CalculatorGcodeArtifact, artifact.id) is None
    assert not expired_blob.exists()
    assert not orphan.exists()
