"""Reading a sliced model line by line, without holding it as a list.

A fifty-megabyte model is a million and a half lines, and the parse reads them
three times over. Building that list once and keeping it alive throughout cost
more than twice the file in memory. The lines are produced on demand now, a
megabyte of text at a time, and these tests hold the new source to the only
standard that matters: it must say exactly what ``str.splitlines`` said.
"""

import gzip
import io
import zipfile

import pytest

from app.services import calculator_gcode_parser as parser
from app.services.calculator_gcode_parser import (
    GcodeLines,
    _iter_gcode_lines,
    parse_gcode_payload,
)

TRICKY_TEXTS = [
    "",
    "one line without an ending",
    "unix\nendings\nthroughout\n",
    "windows\r\nendings\r\nthroughout\r\n",
    "old\rmac\rendings\r",
    "mixed\nendings\r\nin one\rfile\n",
    "trailing newline\n",
    "no trailing newline",
    "\n\n\nempty lines\n\n",
    "\r\n\r\nempty windows lines\r\n",
    "vertical\vtab and\fform feed",
    "unicode separator and paragraph",
    "next\x85line",
    "\r",
    "\n",
    "\r\n",
    "a\r\n\r\nb",
]


@pytest.mark.parametrize("text", TRICKY_TEXTS)
def test_the_line_source_says_exactly_what_splitlines_says(text: str) -> None:
    assert list(_iter_gcode_lines(text)) == text.splitlines()


@pytest.mark.parametrize("text", TRICKY_TEXTS)
@pytest.mark.parametrize("chunk", [1, 2, 3, 7])
def test_line_boundaries_survive_falling_inside_a_chunk(
    monkeypatch: pytest.MonkeyPatch, text: str, chunk: int
) -> None:
    """The text is read in pieces, and a line — or a "\\r\\n" — may straddle two.

    The chunk is made tiny here on purpose: at the real size a boundary lands
    inside a line once every million characters and no test would ever see it.
    """
    monkeypatch.setattr(parser, "_LINE_CHUNK_CHARS", chunk)

    assert list(_iter_gcode_lines(text)) == text.splitlines()


def test_a_carriage_return_split_across_chunks_is_still_one_ending(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The case the chunking has to hold back for: "\\r" ends one piece, "\\n" starts the next."""
    monkeypatch.setattr(parser, "_LINE_CHUNK_CHARS", 3)

    text = "abc\r\ndef"
    assert list(_iter_gcode_lines(text)) == ["abc", "def"] == text.splitlines()


def test_the_same_source_can_be_read_again() -> None:
    """Three passes read the same lines; the source must not be spent by the first."""
    lines = GcodeLines("first\nsecond\nthird\n")

    assert list(lines) == ["first", "second", "third"]
    assert list(lines) == ["first", "second", "third"]


MODEL = """; generated by OrcaSlicer 2.4.0
; total filament used [g] = 128.44
; estimated printing time (normal mode) = 1h 2m 3s
; filament_type = PLA
; layer_height = 0.2
M83
;TYPE:Sparse infill
G1 X10 Y10 E1.5
;TYPE:Support
G1 X20 Y20 E0.5
"""


def test_a_gzip_model_reads_the_same_as_a_plain_one() -> None:
    plain = parse_gcode_payload(
        file_name="model.gcode", raw_bytes=MODEL.encode("utf-8"), plate_index=None
    )
    compressed = parse_gcode_payload(
        file_name="model.gcode.gz",
        raw_bytes=gzip.compress(MODEL.encode("utf-8")),
        plate_index=None,
    )

    for field in ("print_time_seconds", "total_filament_weight_g", "layer_height_mm"):
        assert compressed[field] == plain[field]


def test_an_embedded_thumbnail_is_still_found() -> None:
    """The thumbnail pass reads the whole model and now shares one line source."""
    pixel = (
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
    )
    model = (
        "; generated by OrcaSlicer 2.4.0\n"
        f"; thumbnail begin 16x16 {len(pixel)}\n"
        f"; {pixel}\n"
        "; thumbnail end\n"
        "G1 X1 Y1 E0.1\n"
    )

    parsed = parse_gcode_payload(
        file_name="model.gcode", raw_bytes=model.encode("utf-8"), plate_index=None
    )

    assert parsed["thumbnail_data_url"].startswith("data:image/png;base64,")


def test_a_3mf_model_is_decoded_once(monkeypatch: pytest.MonkeyPatch) -> None:
    """The container used to decode its G-code twice: once to parse, once for roles."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", MODEL)

    decodes = []
    original = parser._decode_gcode_bytes

    def counted(*args, **kwargs):
        decodes.append(1)
        return original(*args, **kwargs)

    monkeypatch.setattr(parser, "_decode_gcode_bytes", counted)

    parsed = parse_gcode_payload(
        file_name="model.gcode.3mf", raw_bytes=buffer.getvalue(), plate_index=None
    )

    assert parsed["container_format"] == "gcode_3mf"
    assert len(decodes) == 1
