"""Quotes from the head and tail of a sliced file instead of the whole upload."""

from __future__ import annotations

import json
import time
from pathlib import Path

import pytest
from httpx import AsyncClient

from app.services import subscription_service
from app.services.calculator_gcode_parser import (
    parse_gcode_3mf_excerpt,
    parse_gcode_excerpt,
    parse_gcode_payload,
)

MIB = 1024 * 1024

_SUMMARY_FIELDS = (
    "slicer_name",
    "slicer_version",
    "print_time_seconds",
    "first_layer_print_time_seconds",
    "total_filament_weight_g",
    "total_filament_length_mm",
    "total_filament_volume_cm3",
    "total_layers",
    "printer_model",
    "printer_settings_id",
    "print_settings_id",
    "nozzle_diameter_mm",
    "nozzle_temperature_first_layer_c",
    "nozzle_temperature_other_layers_c",
    "bed_temperature_first_layer_c",
    "bed_temperature_other_layers_c",
    "layer_height_mm",
    "initial_layer_height_mm",
    "sparse_infill_density_percent",
    "wall_loops",
    "fhub_identities",
    "active_material_count",
    "is_multi_material",
    "object_count",
)
_MATERIAL_FIELDS = (
    "tool_index",
    "type",
    "name",
    "vendor",
    "color",
    "weight_g",
    "length_mm",
    "volume_cm3",
    "density_g_cm3",
    "diameter_mm",
    "settings_id",
)
_PER_TOOLPATH_FIELDS = (
    "infill_filament_weight_g",
    "support_filament_weight_g",
    "brim_filament_weight_g",
    "prime_tower_filament_weight_g",
    "object_filament_weight_g",
    "shared_filament_weight_g",
)


@pytest.fixture(autouse=True)
def _no_paywall(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setitem(subscription_service._settings_cache, "paywall_enforced", False)


def _orca_gcode(size_bytes: int = 6 * MIB) -> bytes:
    header = (
        "; HEADER_BLOCK_START\n"
        "; generated by OrcaSlicer 2.3.0 on 2026-09-01 at 10:00:00 UTC\n"
        "; HEADER_BLOCK_END\n"
        "EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0 CENTER=100,100 POLYGON=[[1,1],[2,2]]\n"
        "M83\n"
    )
    footer = (
        "; filament used [mm] = 5000.00,0.00\n"
        "; filament used [cm3] = 12.00,0.00\n"
        "; filament used [g] = 14.88,0.00\n"
        "; filament cost = 0.30,0.00\n"
        "; total filament used [g] = 14.88\n"
        "; total layers count = 120\n"
        "; estimated first layer printing time (normal mode) = 1m 5s\n"
        "; estimated printing time (normal mode) = 8h 43m 10s\n"
        "; CONFIG_BLOCK_START\n"
        '; filament_settings_id = "Generic PETG";"Generic PLA"\n'
        "; filament_type = PETG;PLA\n"
        '; filament_vendor = "Generic";"Bambu Lab"\n'
        "; filament_colour = #FFFFFF;#000000\n"
        "; filament_density = 1.27,1.24\n"
        "; filament_diameter = 1.75,1.75\n"
        "; filament_id = GFG99;GFA00\n"
        "; fhub_identity_v1 = kind=material_preset;tool=0;id=34059\n"
        "; printer_model = Bambu Lab P1S\n"
        "; printer_settings_id = Bambu Lab P1S 0.4 nozzle\n"
        "; print_settings_id = 0.20mm Standard @BBL X1C\n"
        "; nozzle_diameter = 0.4\n"
        "; nozzle_temperature_initial_layer = 255,215\n"
        "; nozzle_temperature = 250,210\n"
        "; cool_plate_temp_initial_layer = 70,60\n"
        "; cool_plate_temp = 65,55\n"
        "; layer_height = 0.2\n"
        "; initial_layer_print_height = 0.2\n"
        "; sparse_infill_density = 15%\n"
        "; wall_loops = 3\n"
        "; CONFIG_BLOCK_END\n"
    )
    body_unit = (
        "EXCLUDE_OBJECT_START NAME=Cube_id_0\n"
        ";TYPE:Sparse infill\n"
        + "G1 X10.123 Y10.123 E0.0123\n" * 40
        + "EXCLUDE_OBJECT_END\n"
        + ";TYPE:Support\n"
        + "G1 X10.123 Y10.123 E0.0123\n" * 10
    )
    repeats = (size_bytes - len(header) - len(footer)) // len(body_unit) + 1
    return (header + body_unit * repeats + footer).encode()


def _assert_cut_mid_line(raw: bytes, head_end: int, tail_start: int) -> None:
    assert raw[head_end - 1 : head_end] != b"\n"
    assert raw[tail_start - 1 : tail_start] != b"\n"


def test_excerpt_summary_equals_the_full_parse_of_a_large_file() -> None:
    raw = _orca_gcode()
    assert len(raw) > 5 * MIB
    head_end, tail_start = MIB - 3, len(raw) - (4 * MIB - 5)
    _assert_cut_mid_line(raw, head_end, tail_start)

    full = parse_gcode_payload("part.gcode", raw)
    excerpt = parse_gcode_excerpt("part.gcode", len(raw), raw[:head_end], raw[tail_start:])

    assert full["infill_filament_weight_g"] is not None
    assert full["support_filament_weight_g"] is not None
    assert full["print_time_seconds"] == 8 * 3600 + 43 * 60 + 10
    for field in _SUMMARY_FIELDS:
        assert excerpt[field] == full[field], field
    assert excerpt["file_size_bytes"] == len(raw)
    assert [{key: item[key] for key in _MATERIAL_FIELDS} for item in excerpt["materials"]] == [
        {key: item[key] for key in _MATERIAL_FIELDS} for item in full["materials"]
    ]
    assert excerpt["materials"][0]["vendor"] == "Generic"

    assert excerpt["detail_level"] == "summary"
    assert "detail_level" not in full
    for field in _PER_TOOLPATH_FIELDS:
        assert excerpt[field] is None, field
    assert excerpt["support_roles_detected"] == []
    assert all(
        group["extrusion_share"] is None and group["material_weights_g"] == {}
        for group in excerpt["object_groups"]
    )
    assert all("infill_weight_g" not in item for item in excerpt["materials"])


def test_a_line_cut_in_half_is_dropped_but_a_file_cut_without_a_gap_is_whole() -> None:
    raw = (
        b"; generated by OrcaSlicer 2.3.0\n"
        b"; estimated printing time (normal mode) = 1h\n"
        b"; total filament used [g] = 25.5\n"
        + b"G1 X1 Y1 E1\n" * 3
        + b"; layer_height = 0.2\n"
    )
    cut = raw.index(b"= 25.5") + len(b"= 2")

    contiguous = parse_gcode_excerpt("a.gcode", len(raw), raw[:cut], raw[cut:])
    with_gap = parse_gcode_excerpt("a.gcode", len(raw) + 50, raw[:cut], raw[cut + 10 :])

    assert contiguous["total_filament_weight_g"] == 25.5
    assert with_gap["total_filament_weight_g"] is None
    assert with_gap["print_time_seconds"] == 3600


_SLICE_INFO = """<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header><header_item key="X-BBL-Client-Type" value="slicer"/></header>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="printer_model_id" value="C12"/>
    <metadata key="nozzle_diameters" value="0.4"/>
    <metadata key="prediction" value="3150"/>
    <metadata key="weight" value="12.5"/>
    <metadata key="support_used" value="false"/>
    <object identify_id="1" name="Cube" skipped="false"/>
    <filament id="1" tray_info_idx="GFA00" type="PLA" color="#FFFFFF" used_m="4.19" used_g="12.5"/>
  </plate>
  <plate>
    <metadata key="index" value="2"/>
    <metadata key="prediction" value="600"/>
    <metadata key="weight" value="3.2"/>
    <metadata key="support_used" value="true"/>
    <filament id="2" tray_info_idx="GFG99" type="PETG" color="#000000" used_m="1.1" used_g="3.2"/>
  </plate>
</config>
"""

_PROJECT_SETTINGS = {
    "printer_model": "Bambu Lab P1S",
    "printer_settings_id": "Bambu Lab P1S 0.4 nozzle",
    "print_settings_id": "0.20mm Standard @BBL X1C",
    "filament_settings_id": ["Generic PLA", "Generic PETG"],
    "filament_type": ["PLA", "PETG"],
    "filament_vendor": ["Bambu Lab", "Generic"],
    "filament_density": ["1.24", "1.27"],
    "nozzle_diameter": ["0.4"],
    "nozzle_temperature": ["220", "250"],
    "layer_height": "0.2",
    "machine_start_gcode": "M104 S0\nSET_PRINT_STATS_INFO TOTAL_LAYER=5\nG28",
}
_PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 16


def test_slice_info_filament_id_beyond_the_tool_limit_is_ignored() -> None:
    slice_info = _SLICE_INFO.replace(
        '<filament id="2" tray_info_idx="GFG99"',
        '<filament id="1000000000" tray_info_idx="GFG99"',
    )

    started = time.perf_counter()
    first, second = parse_gcode_3mf_excerpt(
        "a.gcode.3mf", 1000, {"metadata/slice_info.config": slice_info.encode()}
    )

    assert time.perf_counter() - started < 2
    assert [item["tool_index"] for item in first["materials"]] == [0]
    assert all(item["tool_index"] <= 255 for item in second["materials"])
    assert second["total_filament_weight_g"] == 3.2


def _form(container: str, file_name: str, size: int = 123456) -> dict[str, str]:
    return {"file_name": file_name, "file_size_bytes": str(size), "container": container}


def _entry(path: str, payload: bytes) -> tuple[str, tuple[str, bytes, str]]:
    return ("entry", (path, payload, "application/octet-stream"))


@pytest.mark.asyncio
async def test_sliced_3mf_entries_give_one_job_per_plate(auth_client: AsyncClient) -> None:
    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse",
        data=_form("gcode_3mf", "two-plates.gcode.3mf"),
        files=[
            _entry("Metadata:slice_info.config", _SLICE_INFO.encode()),
            _entry("Metadata/project_settings.config", json.dumps(_PROJECT_SETTINGS).encode()),
            _entry("Metadata/model_settings.config", b"<config/>"),
            _entry("Metadata/plate_1.json", b"{}"),
            _entry("Metadata/plate_1.png", _PNG),
            _entry("Metadata/plate_2_small.png", _PNG + b"\x01"),
        ],
    )

    assert response.status_code == 200
    first, second = response.json()["jobs"]
    assert [first["plate_index"], second["plate_index"]] == [1, 2]
    assert first["available_plate_indices"] == [1, 2]
    assert (first["print_time_seconds"], second["print_time_seconds"]) == (3150, 600)
    assert (first["total_filament_weight_g"], second["total_filament_weight_g"]) == (12.5, 3.2)
    assert first["container_format"] == second["container_format"] == "gcode_3mf"
    assert first["detail_level"] == second["detail_level"] == "summary"
    assert first["file_name"] == "two-plates.gcode.3mf"
    assert first["file_size_bytes"] == 123456
    assert first["printer_model"] == "Bambu Lab P1S"
    assert first["printer_settings_id"] == "Bambu Lab P1S 0.4 nozzle"
    assert first["nozzle_diameter_mm"] == 0.4
    assert first["layer_height_mm"] == 0.2
    assert first["support_used"] is False
    assert second["support_used"] is True
    assert first["thumbnail_data_url"].startswith("data:image/png;base64,")

    [first_material] = first["materials"]
    assert (first_material["tool_index"], first_material["type"]) == (0, "PLA")
    assert (first_material["name"], first_material["vendor"]) == ("Generic PLA", "Bambu Lab")
    assert (first_material["weight_g"], first_material["density_g_cm3"]) == (12.5, 1.24)
    [second_material] = second["materials"]
    assert (second_material["tool_index"], second_material["type"]) == (1, "PETG")
    assert (second_material["name"], second_material["vendor"]) == ("Generic PETG", "Generic")
    assert second_material["weight_g"] == 3.2


@pytest.mark.asyncio
async def test_plain_excerpt_parts_are_parsed_through_the_endpoint(
    auth_client: AsyncClient,
) -> None:
    raw = _orca_gcode(3 * MIB)
    head, tail = raw[: MIB - 3], raw[MIB:]

    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse",
        data=_form("plain_gcode", "big.gcode", len(raw)),
        files=[
            ("head", ("big.gcode", head, "application/octet-stream")),
            ("tail", ("big.gcode", tail, "application/octet-stream")),
        ],
    )

    assert response.status_code == 200
    [job] = response.json()["jobs"]
    assert job["print_time_seconds"] == 8 * 3600 + 43 * 60 + 10
    assert job["total_filament_weight_g"] == 14.88
    assert job["file_size_bytes"] == len(raw)
    assert job["detail_level"] == "summary"


_FIXTURES = Path(__file__).parent / "fixtures" / "gcode_toolpath_parity"
_FIXTURE_GCODE = (_FIXTURES / "toolpath.gcode").read_bytes()
_FIXTURE_TOOLPATH = (_FIXTURES / "expected_evidence.json").read_text(encoding="utf-8")


def _plain_parts(raw: bytes) -> list:
    return [("head", ("toolpath.gcode", raw, "application/octet-stream"))]


@pytest.mark.asyncio
async def test_a_plain_excerpt_with_the_toolpath_gets_the_per_part_weights(
    auth_client: AsyncClient,
) -> None:
    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse",
        data={**_form("plain_gcode", "toolpath.gcode", len(_FIXTURE_GCODE)), "toolpath": _FIXTURE_TOOLPATH},
        files=_plain_parts(_FIXTURE_GCODE),
    )

    assert response.status_code == 200
    [job] = response.json()["jobs"]
    assert job["detail_level"] == "full"
    assert job["toolchange_count"] == 2
    assert job["support_roles_detected"] == ["support", "support interface"]
    shares = {group["name"]: group["extrusion_share"] for group in job["object_groups"]}
    assert set(shares) == {"Cube", "Bracket id 2"}
    assert sum(shares.values()) == pytest.approx(1.0, abs=1e-5)
    assert job["prime_tower_filament_weight_g"] > 0
    assert job["brim_filament_weight_g"] > 0


@pytest.mark.asyncio
async def test_a_3mf_excerpt_takes_the_toolpath_of_each_plate_it_names(
    auth_client: AsyncClient,
) -> None:
    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse",
        data={
            **_form("gcode_3mf", "two-plates.gcode.3mf"),
            "toolpath": json.dumps({"2": json.loads(_FIXTURE_TOOLPATH)}),
        },
        files=[
            _entry("Metadata/slice_info.config", _SLICE_INFO.encode()),
            _entry("Metadata/project_settings.config", json.dumps(_PROJECT_SETTINGS).encode()),
        ],
    )

    assert response.status_code == 200
    first, second = response.json()["jobs"]
    assert (first["detail_level"], second["detail_level"]) == ("summary", "full")
    assert first["object_groups"] == []
    assert second["support_roles_detected"] == ["support", "support interface"]
    assert second["toolchange_count"] == 2


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("container", "toolpath"),
    [
        pytest.param("plain_gcode", "{", id="not-json"),
        pytest.param("plain_gcode", "[]", id="not-an-object"),
        pytest.param("plain_gcode", "", id="empty"),
        pytest.param("plain_gcode", "[" * 100_000, id="deeply-nested"),
        pytest.param(
            "plain_gcode",
            _FIXTURE_TOOLPATH.replace('"brim": 1.2', '"brim": NaN'),
            id="not-a-number",
        ),
        pytest.param(
            "plain_gcode",
            json.dumps({"1": json.loads(_FIXTURE_TOOLPATH)}),
            id="plate-map-for-plain-gcode",
        ),
        pytest.param("gcode_3mf", _FIXTURE_TOOLPATH, id="plain-evidence-for-3mf"),
        pytest.param(
            "gcode_3mf",
            json.dumps({"first": json.loads(_FIXTURE_TOOLPATH)}),
            id="plate-key-not-a-number",
        ),
        pytest.param(
            "gcode_3mf",
            json.dumps({"0": json.loads(_FIXTURE_TOOLPATH)}),
            id="plate-zero",
        ),
    ],
)
async def test_a_toolpath_that_breaks_the_contract_refuses_the_request(
    auth_client: AsyncClient,
    container: str,
    toolpath: str,
) -> None:
    if container == "plain_gcode":
        data = {**_form(container, "toolpath.gcode", len(_FIXTURE_GCODE)), "toolpath": toolpath}
        files = _plain_parts(_FIXTURE_GCODE)
    else:
        data = {**_form(container, "a.gcode.3mf"), "toolpath": toolpath}
        files = [_entry("Metadata/slice_info.config", _SLICE_INFO.encode())]

    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse", data=data, files=files
    )

    assert response.status_code == 400
    assert response.json()["detail"]["code"] == "ERR_GCODE_EXCERPT_INVALID"


@pytest.mark.asyncio
async def test_a_toolpath_over_its_cap_is_refused_as_too_large(auth_client: AsyncClient) -> None:
    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse",
        data={
            **_form("plain_gcode", "toolpath.gcode", len(_FIXTURE_GCODE)),
            "toolpath": " " * (256 * 1024 + 1),
        },
        files=_plain_parts(_FIXTURE_GCODE),
    )

    assert response.status_code == 413
    assert response.json()["detail"]["code"] == "ERR_GCODE_EXCERPT_TOO_LARGE"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("files", "data", "status_code", "code"),
    [
        pytest.param(
            [("head", ("a.gcode", b";" + b"x" * MIB, "text/plain"))],
            _form("plain_gcode", "a.gcode"),
            413,
            "ERR_GCODE_EXCERPT_TOO_LARGE",
            id="head-over-cap",
        ),
        pytest.param(
            [
                ("head", ("a.gcode", b"; x\n", "text/plain")),
                ("tail", ("a.gcode", b";" + b"x" * (4 * MIB), "text/plain")),
            ],
            _form("plain_gcode", "a.gcode"),
            413,
            "ERR_GCODE_EXCERPT_TOO_LARGE",
            id="tail-over-cap",
        ),
        pytest.param(
            [
                _entry("Metadata/slice_info.config", _SLICE_INFO.encode()),
                _entry("Metadata/plate_1.gcode", b"G1 X1 E1\n"),
            ],
            _form("gcode_3mf", "a.gcode.3mf"),
            400,
            "ERR_GCODE_EXCERPT_INVALID",
            id="gcode-entry-refused",
        ),
        pytest.param(
            [
                _entry("Metadata/slice_info.config", _SLICE_INFO.encode()),
                _entry("metadata/SLICE_INFO.config", _SLICE_INFO.encode()),
            ],
            _form("gcode_3mf", "a.gcode.3mf"),
            400,
            "ERR_GCODE_EXCERPT_INVALID",
            id="duplicate-entry",
        ),
        pytest.param(
            [_entry("Metadata/plate_1.json", b"{}")],
            _form("gcode_3mf", "a.gcode.3mf"),
            400,
            "ERR_GCODE_EXCERPT_INVALID",
            id="3mf-without-slice-info",
        ),
        pytest.param(
            [("head", ("a.gcode", b"; x\n", "text/plain"))],
            _form("zip", "a.gcode"),
            400,
            "ERR_GCODE_EXCERPT_INVALID",
            id="unknown-container",
        ),
        pytest.param(
            [("head", ("a.gcode", b"; just a note\nG1 X1 Y1\n", "text/plain"))],
            _form("plain_gcode", "a.gcode"),
            400,
            "ERR_GCODE_PARSE_FAILED",
            id="no-slicer-summary",
        ),
    ],
)
async def test_excerpt_contract_violations_are_refused(
    auth_client: AsyncClient,
    files: list,
    data: dict[str, str],
    status_code: int,
    code: str,
) -> None:
    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse",
        data=data,
        files=files,
    )

    assert response.status_code == status_code
    assert response.json()["detail"]["code"] == code


@pytest.mark.asyncio
async def test_excerpt_body_over_the_request_cap_is_refused_before_reading(
    auth_client: AsyncClient,
) -> None:
    response = await auth_client.post(
        "/api/v1/calculator/gcode-excerpts/parse",
        content=b"x" * (24 * MIB + 1),
        headers={"Content-Type": "multipart/form-data; boundary=x"},
    )

    assert response.status_code == 413
    assert response.json()["detail"]["code"] == "ERR_GCODE_EXCERPT_TOO_LARGE"
