"""Leftovers of the retired upload path still expire; the parser stays cancellable."""

from __future__ import annotations

import io
import os
import warnings
import zipfile
from datetime import datetime, timedelta, timezone
from uuid import uuid4

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.calculator_gcode_artifact import CalculatorGcodeArtifact
from app.models.user import User
from app.services import calculator_gcode_artifact_service as artifacts
from app.services.calculator_gcode_parser import GcodeParseCancelled, parse_gcode_payload


def _plain_gcode() -> bytes:
    return (
        "; generated by OrcaSlicer 2.4.0\n"
        "; estimated printing time (normal mode) = 1h 2m\n"
        "; total filament weight [g] : 12.5\n"
        "; filament_type = PLA\n"
        "; filament_settings_id = Generic PLA\n"
    ).encode()


@pytest.fixture
def artifact_storage(tmp_path, monkeypatch: pytest.MonkeyPatch):
    root = tmp_path / "calculator-gcode"
    monkeypatch.setattr(artifacts, "artifact_storage_root", lambda: root)
    return root


def test_parser_cooperatively_stops_during_a_large_plain_file() -> None:
    payload = ("; generated by OrcaSlicer 2.4.0\n" + "G1 X1 E0.1\n" * 300_000).encode()
    checks = 0

    def cancelled() -> bool:
        nonlocal checks
        checks += 1
        return checks >= 3

    with pytest.raises(GcodeParseCancelled):
        parse_gcode_payload("cancel.gcode", payload, should_cancel=cancelled)


def test_duplicate_plate_names_are_rejected() -> None:
    output = io.BytesIO()
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore",
            message=r"Duplicate name: 'Metadata/plate_1\.gcode'",
            category=UserWarning,
            module="zipfile",
        )
        with zipfile.ZipFile(output, "w") as archive:
            archive.writestr("Metadata/plate_1.gcode", _plain_gcode())
            archive.writestr("Metadata/plate_1.gcode", _plain_gcode())
    with pytest.raises(ValueError, match="duplicate_plate"):
        parse_gcode_payload("duplicate.gcode.3mf", output.getvalue())


@pytest.mark.asyncio
async def test_cleanup_removes_expired_rows_and_old_orphan_files(
    db_session: AsyncSession,
    artifact_storage,
    auth_user: User,
) -> None:
    now = datetime.now(timezone.utc)
    artifact_storage.mkdir(parents=True)
    expired_blob = artifact_storage / f"{uuid4()}.bin"
    expired_blob.write_bytes(_plain_gcode())
    artifact = CalculatorGcodeArtifact(
        id=expired_blob.stem,
        owner_user_id=auth_user.id,
        original_name="expired.gcode",
        expected_size_bytes=expired_blob.stat().st_size,
        size_bytes=expired_blob.stat().st_size,
        sha256="0" * 64,
        storage_key=expired_blob.name,
        state="ready",
        expires_at=now - timedelta(seconds=1),
    )
    db_session.add(artifact)
    await db_session.commit()

    orphan = artifact_storage / f"{uuid4()}.1.part"
    orphan.write_bytes(b"partial")
    old_timestamp = (now - artifacts.ORPHAN_FILE_GRACE - timedelta(seconds=1)).timestamp()
    orphan.touch()
    os.utime(orphan, (old_timestamp, old_timestamp))

    removed = await artifacts.cleanup_expired_artifacts(db_session, now=now)
    await db_session.commit()

    assert removed == 1
    assert await db_session.get(CalculatorGcodeArtifact, artifact.id) is None
    assert not expired_blob.exists()
    assert not orphan.exists()
