"""Regression tests for Calculator Pro G-code analysis."""

from __future__ import annotations

import io
import zipfile

import pytest

from app.services.calculator_gcode_parser import parse_gcode_payload


def _build_gcode_3mf() -> bytes:
    archive_bytes = io.BytesIO()
    slice_info = """<?xml version="1.0" encoding="UTF-8"?>
<config>
  <plate>
    <metadata key="index" value="1" />
    <metadata key="prediction" value="120" />
    <metadata key="weight" value="4.20" />
    <metadata key="support_used" value="false" />
    <filament id="1" tray_info_idx="PLA Basic" type="PLA" color="#000000" used_m="1.40" used_g="4.20" used_for_object="true" used_for_support="false" />
  </plate>
  <plate>
    <metadata key="index" value="2" />
    <metadata key="prediction" value="300" />
    <metadata key="weight" value="8.50" />
    <metadata key="support_used" value="true" />
    <filament id="2" tray_info_idx="PETG Support" type="PETG" color="#FFFFFF" used_m="2.50" used_g="8.50" used_for_object="true" used_for_support="true" />
  </plate>
</config>
"""
    with zipfile.ZipFile(archive_bytes, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "Metadata/plate_1.gcode",
            (
                "; generated by OrcaSlicer 2.4.0\n"
                "M83\n"
                ";TYPE:Sparse infill\n"
                "G1 X1 E3\n"
                ";TYPE:Outer wall\n"
                "G1 X2 E1\n"
            ),
        )
        archive.writestr(
            "Metadata/plate_2.gcode",
            "; generated by OrcaSlicer 2.4.0\n;TYPE:Support\n; total filament weight [g] : 0,8.50\n",
        )
        archive.writestr("Metadata/slice_info.config", slice_info)
        archive.writestr("Metadata/plate_2.png", b"\x89PNG\r\n\x1a\ncalculator-preview")
    return archive_bytes.getvalue()


def test_plain_gcode_preserves_sparse_tool_metadata_and_analysis_fields() -> None:
    gcode = """; generated by OrcaSlicer 2.3.1
; total filament length [mm] : 0,12658.54
; total filament volume [cm^3] : 0,30.45
; total filament weight [g] : 0,38.67
; filament_type = ABS;PETG
; filament_settings_id = ABS;"Generic PETG @System - Copy"
; filament_vendor = Generic;Acme
; filament_colour = #000000;#977168
; filament_ids = GFB99;GFG99
; filament cost = 0,1.16
; filament_cost = 20,30
; filament_density = 1.04,1.27
; filament_diameter = 1.75,1.75
; filament_flow_ratio = 0.926,1
; filament_max_volumetric_speed = 18,12
; filament_prime_volume = 45,50
; prime_volume = 60
; filament_is_support = 0,1
; outer_wall_line_width = 0.42
; inner_wall_line_width = 0.45
; outer_wall_speed = 120
; inner_wall_speed = 200
; sparse_infill_speed = 250
; support_speed = 150
; initial_layer_speed = 50
;TYPE:Support interface
"""

    parsed = parse_gcode_payload("job.gcode", gcode.encode())

    assert parsed["total_filament_weight_g"] == 38.67
    assert parsed["total_filament_length_mm"] == 12658.54
    assert parsed["total_filament_volume_cm3"] == 30.45
    assert parsed["support_used"] is True
    assert parsed["support_roles_detected"] == ["support interface"]
    assert parsed["outer_wall_line_width_mm"] == 0.42
    assert parsed["support_speed_mm_s"] == 150.0
    assert parsed["prime_volume_mm3"] == 60.0
    assert parsed["materials"] == [
        {
            "tool_index": 1,
            "type": "PETG",
            "name": "Generic PETG @System - Copy",
            "vendor": "Acme",
            "color": "#977168",
            "weight_g": 38.67,
            "length_mm": 12658.54,
            "volume_cm3": 30.45,
            "density_g_cm3": 1.27,
            "diameter_mm": 1.75,
            "slicer_filament_id": "GFG99",
            "slicer_usage_cost": 1.16,
            "slicer_profile_price_per_kg": 30.0,
            "flow_ratio": 1.0,
            "max_volumetric_speed_mm3_s": 12.0,
            "prime_volume_mm3": 50.0,
            "is_support_material": True,
            "used_for_model": None,
            "used_for_support": None,
            "settings_id": "Generic PETG @System - Copy",
        }
    ]


def test_plain_gcode_preserves_multiple_used_materials() -> None:
    gcode = """; generated by OrcaSlicer 2.4.0
; total filament weight [g] : 12.5,4.25
; filament_type = PLA;PETG
; filament_settings_id = Model PLA;Support PETG
; filament_vendor = Acme;Acme
; filament_colour = #111111;#EEEEEE
; filament_cost = 800;1600
; filament_density = 1.24;1.27
; filament_diameter = 1.75;1.75
; filament_is_support = 0;1
; total toolchanges = 9
"""

    parsed = parse_gcode_payload("multi-material.gcode", gcode.encode())

    assert parsed["total_filament_weight_g"] == 16.75
    assert parsed["active_material_count"] == 2
    assert parsed["is_multi_material"] is True
    assert parsed["toolchange_count"] == 9
    assert [(item["tool_index"], item["weight_g"]) for item in parsed["materials"]] == [
        (0, 12.5),
        (1, 4.25),
    ]
    assert parsed["materials"][1]["is_support_material"] is True


def test_orca_time_does_not_add_fractional_first_layer_to_total() -> None:
    gcode = """; generated by OrcaSlicer 2.4.0
; estimated printing time (normal mode) = 6h 10m 44s
; estimated first layer printing time (normal mode) = 0.740191s
"""

    parsed = parse_gcode_payload("time.gcode", gcode.encode())

    assert parsed["print_time_seconds"] == 22_244
    assert parsed["first_layer_print_time_seconds"] == 1


def test_role_weights_use_real_relative_extrusion_and_ignore_retractions() -> None:
    gcode = """; generated by OrcaSlicer 2.4.0
; total filament weight [g] : 0,10
; filament_type = PETG
; filament_settings_id = Generic PETG
M83
;TYPE:Outer wall
G1 X1 E2
G1 E-.8
G1 E.8
;TYPE:Sparse infill
G1 X2 E3
;TYPE:Internal solid infill
G1 X3 E1
;TYPE:Support
G1 X4 E2
;TYPE:Top surface
G1 X5 E2
"""

    parsed = parse_gcode_payload("roles-relative.gcode", gcode.encode())

    assert parsed["infill_filament_weight_g"] == 4.0
    assert parsed["support_filament_weight_g"] == 2.0
    assert parsed["materials"][0]["infill_weight_g"] == 4.0
    assert parsed["materials"][0]["support_weight_g"] == 2.0


def test_role_weights_support_absolute_extrusion_resets_and_multiple_tools() -> None:
    gcode = """; generated by OrcaSlicer 2.4.0
; total filament weight [g] : 8,4
; filament_type = PLA;PETG
; filament_settings_id = Model PLA;Support PETG
M82
T0
G92 E0
;TYPE:Outer wall
G1 X1 E2
G1 E1
G1 E2
;TYPE:Sparse infill
G1 X2 E6
T1
G92 E0
;TYPE:Support interface
G1 X3 E4
"""

    parsed = parse_gcode_payload("roles-absolute.gcode", gcode.encode())

    assert parsed["infill_filament_weight_g"] == 5.333
    assert parsed["support_filament_weight_g"] == 4.0
    assert parsed["materials"][0]["infill_weight_g"] == 5.333
    assert parsed["materials"][1]["support_weight_g"] == 4.0


def test_exclude_object_groups_keep_instances_with_shared_centers() -> None:
    gcode = """; generated by OrcaSlicer 2.4.0
; total filament weight [g] : 0.12
; filament_type = PLA
; filament_settings_id = Generic PLA
EXCLUDE_OBJECT_DEFINE NAME=Gear_id_0_copy_0 CENTER=10,10
EXCLUDE_OBJECT_DEFINE NAME=Gear_id_1_copy_0 CENTER=10,10
EXCLUDE_OBJECT_DEFINE NAME=Cover.stl_id_2_copy_0 CENTER=20,20
M83
EXCLUDE_OBJECT_START NAME=Gear_id_0_copy_0
;TYPE:Outer wall
G1 X1 E2
EXCLUDE_OBJECT_END NAME=Gear_id_0_copy_0
EXCLUDE_OBJECT_START NAME=Gear_id_1_copy_0
G1 X2 E2
EXCLUDE_OBJECT_END NAME=Gear_id_1_copy_0
EXCLUDE_OBJECT_START NAME=Cover.stl_id_2_copy_0
G1 X3 E8
EXCLUDE_OBJECT_END NAME=Cover.stl_id_2_copy_0
"""

    parsed = parse_gcode_payload("objects.gcode", gcode.encode())

    assert parsed["object_count"] == 3
    assert parsed["object_groups"] == [
        {
            "name": "Cover",
            "count": 1,
            "extrusion_share": 0.666667,
            "material_weights_g": {0: 0.08},
        },
        {
            "name": "Gear",
            "count": 2,
            "extrusion_share": 0.333333,
            "material_weights_g": {0: 0.04},
        },
    ]


def test_object_groups_keep_per_tool_material_weight() -> None:
    gcode = """; generated by OrcaSlicer 2.4.0
; total filament weight [g] : 10,20
; filament_type = PLA,PETG
; filament_settings_id = Red PLA,White PETG
EXCLUDE_OBJECT_DEFINE NAME=Body_id_0_copy_0 CENTER=10,10
EXCLUDE_OBJECT_DEFINE NAME=Clip_id_1_copy_0 CENTER=20,20
M83
EXCLUDE_OBJECT_START NAME=Body_id_0_copy_0
T0
G1 X1 E10
T1
G1 X2 E5
EXCLUDE_OBJECT_END NAME=Body_id_0_copy_0
EXCLUDE_OBJECT_START NAME=Clip_id_1_copy_0
T1
G1 X3 E15
EXCLUDE_OBJECT_END NAME=Clip_id_1_copy_0
"""

    parsed = parse_gcode_payload("multi-tool-objects.gcode", gcode.encode())

    assert parsed["object_groups"] == [
        {
            "name": "Body",
            "count": 1,
            "extrusion_share": 0.5,
            "material_weights_g": {0: 10.0, 1: 5.0},
        },
        {
            "name": "Clip",
            "count": 1,
            "extrusion_share": 0.5,
            "material_weights_g": {1: 15.0},
        },
    ]


@pytest.mark.parametrize(
    ("banner", "expected_name"),
    [
        ("generated by OrcaSlicer 2.4.0", "OrcaSlicer"),
        ("generated by BambuStudio 2.3.0", "BambuStudio"),
        ("generated by PrusaSlicer 2.9.2", "PrusaSlicer"),
        ("generated by SuperSlicer 2.5.60", "SuperSlicer"),
        ("generated by CuraEngine 5.10.0", "Cura"),
        ("generated by Creality Print 6.1.0", "CrealitySlicer"),
    ],
)
def test_detects_supported_slicer_families(banner: str, expected_name: str) -> None:
    parsed = parse_gcode_payload("job.gcode", f"; {banner}\n; TIME:60\n".encode())

    assert parsed["slicer_name"] == expected_name


def test_gcode_3mf_lists_plates_and_parses_selected_plate() -> None:
    parsed = parse_gcode_payload("multi.gcode.3mf", _build_gcode_3mf(), plate_index=2)

    assert parsed["container_format"] == "gcode_3mf"
    assert parsed["plate_index"] == 2
    assert parsed["available_plate_indices"] == [1, 2]
    assert parsed["print_time_seconds"] == 300
    assert parsed["total_filament_weight_g"] == 8.5
    assert parsed["support_used"] is True
    assert parsed["thumbnail_data_url"].startswith("data:image/png;base64,")
    assert parsed["materials"][0]["tool_index"] == 1
    assert parsed["materials"][0]["settings_id"] == "PETG Support"
    assert parsed["materials"][0]["used_for_support"] is True
    assert parsed["materials"][0]["is_support_material"] is True


def test_gcode_3mf_uses_first_plate_by_default() -> None:
    parsed = parse_gcode_payload("multi.gcode.3mf", _build_gcode_3mf())

    assert parsed["plate_index"] == 1
    assert parsed["print_time_seconds"] == 120
    assert parsed["support_used"] is False
    assert parsed["materials"][0]["tool_index"] == 0
    assert parsed["infill_filament_weight_g"] == 3.15


def test_gcode_3mf_rejects_unknown_plate() -> None:
    with pytest.raises(ValueError, match="gcode_3mf_plate_not_found"):
        parse_gcode_payload("multi.gcode.3mf", _build_gcode_3mf(), plate_index=99)


def test_gcode_3mf_rejects_archive_without_sliced_plate() -> None:
    archive_bytes = io.BytesIO()
    with zipfile.ZipFile(archive_bytes, "w") as archive:
        archive.writestr("3D/3dmodel.model", "not sliced")

    with pytest.raises(ValueError, match="gcode_3mf_has_no_gcode"):
        parse_gcode_payload("model.gcode.3mf", archive_bytes.getvalue())


def test_gcode_3mf_ignores_unsafe_slice_info_xml() -> None:
    archive_bytes = io.BytesIO()
    with zipfile.ZipFile(archive_bytes, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", "; generated by OrcaSlicer 2.4.0\n")
        archive.writestr(
            "Metadata/slice_info.config",
            '<!DOCTYPE config [<!ENTITY x "unsafe">]><config><plate /></config>',
        )

    parsed = parse_gcode_payload("unsafe.gcode.3mf", archive_bytes.getvalue())

    assert parsed["container_format"] == "gcode_3mf"
    assert parsed["plate_index"] == 1
