"""add_user_model

Revision ID: 0b9a467f6918
Revises: 1a99f4734fc4
Create Date: 2025-10-31 13:38:29.147505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9a467f6918'
down_revision: Union[str, None] = '1a99f4734fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types first (PostgreSQL)
    op.execute("CREATE TYPE userrole AS ENUM ('user', 'brand', 'admin')")
    op.execute("CREATE TYPE presetmoderationstatus AS ENUM ('pending', 'approved', 'rejected')")
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'brand', 'admin', name='userrole', create_type=False), nullable=False, server_default='user'),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_brand_id'), 'users', ['brand_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Add columns to presets table
    op.add_column('presets', sa.Column('moderation_status', sa.Enum('pending', 'approved', 'rejected', name='presetmoderationstatus', create_type=False), nullable=False, server_default='pending'))
    op.add_column('presets', sa.Column('moderation_reason', sa.Text(), nullable=True))
    op.add_column('presets', sa.Column('moderated_by', sa.Integer(), nullable=True))
    op.add_column('presets', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_presets_moderation_status'), 'presets', ['moderation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presets_moderation_status'), table_name='presets')
    op.drop_column('presets', 'moderated_at')
    op.drop_column('presets', 'moderated_by')
    op.drop_column('presets', 'moderation_reason')
    op.drop_column('presets', 'moderation_status')
    
    # Drop ENUM types (PostgreSQL)
    op.execute("DROP TYPE IF EXISTS presetmoderationstatus")
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_brand_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    
    # Drop ENUM type (PostgreSQL)
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###

