"""add_user_model

Revision ID: 0b9a467f6918
Revises: 1a99f4734fc4
Create Date: 2025-10-31 13:38:29.147505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9a467f6918'
down_revision: Union[str, None] = '1a99f4734fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types first (PostgreSQL) - with check for existence
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE userrole AS ENUM ('user', 'brand', 'admin');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE presetmoderationstatus AS ENUM ('pending', 'approved', 'rejected');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Создаем таблицу users через SQL напрямую, чтобы избежать проблем с ENUM
    # SQLAlchemy не видит ENUM, созданный через op.execute() в той же транзакции
    op.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            email VARCHAR(255) NOT NULL UNIQUE,
            username VARCHAR(100) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            role userrole NOT NULL DEFAULT 'user',
            api_key VARCHAR(64) UNIQUE,
            full_name VARCHAR(255),
            bio TEXT,
            active BOOLEAN NOT NULL DEFAULT true,
            email_verified BOOLEAN NOT NULL DEFAULT false,
            brand_id INTEGER,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            last_login TIMESTAMP WITH TIME ZONE
        )
    """)
    
    # Создаем индексы
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_brand_id'), 'users', ['brand_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Add columns to presets table
    # Используем SQL напрямую для добавления колонки с ENUM, чтобы избежать проблем с транзакциями
    op.execute("""
        ALTER TABLE presets 
        ADD COLUMN IF NOT EXISTS moderation_status presetmoderationstatus NOT NULL DEFAULT 'pending',
        ADD COLUMN IF NOT EXISTS moderation_reason TEXT,
        ADD COLUMN IF NOT EXISTS moderated_by INTEGER,
        ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMP WITH TIME ZONE
    """)
    op.create_index(op.f('ix_presets_moderation_status'), 'presets', ['moderation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presets_moderation_status'), table_name='presets')
    op.drop_column('presets', 'moderated_at')
    op.drop_column('presets', 'moderated_by')
    op.drop_column('presets', 'moderation_reason')
    op.drop_column('presets', 'moderation_status')
    
    # Drop ENUM types (PostgreSQL)
    op.execute("DROP TYPE IF EXISTS presetmoderationstatus")
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_brand_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    
    # Drop ENUM type (PostgreSQL)
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###

