"""Initial migration: Brand, Filament, Preset models

Revision ID: 1a99f4734fc4
Revises: 
Create Date: 2025-10-31 11:06:24.821616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a99f4734fc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_active'), 'brands', ['active'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_index(op.f('ix_brands_verified'), 'brands', ['verified'], unique=False)
    op.create_table('filaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('color_name', sa.String(length=100), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('spool_weight', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filaments_active'), 'filaments', ['active'], unique=False)
    op.create_index(op.f('ix_filaments_brand_id'), 'filaments', ['brand_id'], unique=False)
    op.create_index(op.f('ix_filaments_id'), 'filaments', ['id'], unique=False)
    op.create_index(op.f('ix_filaments_material_type'), 'filaments', ['material_type'], unique=False)
    op.create_index(op.f('ix_filaments_name'), 'filaments', ['name'], unique=False)
    op.create_index(op.f('ix_filaments_slug'), 'filaments', ['slug'], unique=True)
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('extruder_temp', sa.Float(), nullable=False),
    sa.Column('bed_temp', sa.Float(), nullable=False),
    sa.Column('print_speed', sa.Float(), nullable=False),
    sa.Column('travel_speed', sa.Float(), nullable=True),
    sa.Column('layer_height', sa.Float(), nullable=True),
    sa.Column('first_layer_height', sa.Float(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('fan_speed', sa.Integer(), nullable=True),
    sa.Column('retraction_length', sa.Float(), nullable=True),
    sa.Column('retraction_speed', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presets_active'), 'presets', ['active'], unique=False)
    op.create_index(op.f('ix_presets_filament_id'), 'presets', ['filament_id'], unique=False)
    op.create_index(op.f('ix_presets_id'), 'presets', ['id'], unique=False)
    op.create_index(op.f('ix_presets_is_official'), 'presets', ['is_official'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presets_is_official'), table_name='presets')
    op.drop_index(op.f('ix_presets_id'), table_name='presets')
    op.drop_index(op.f('ix_presets_filament_id'), table_name='presets')
    op.drop_index(op.f('ix_presets_active'), table_name='presets')
    op.drop_table('presets')
    op.drop_index(op.f('ix_filaments_name'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_material_type'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_id'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_brand_id'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_active'), table_name='filaments')
    op.drop_table('filaments')
    op.drop_index(op.f('ix_brands_verified'), table_name='brands')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_active'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###

