"""add_user_id_to_presets

Revision ID: 47f92b78c02f
Revises: 97585b264440
Create Date: 2025-11-01 07:09:25.503791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f92b78c02f'
down_revision: Union[str, None] = '97585b264440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_presets_user_id'), 'presets', ['user_id'], unique=False)
    op.create_foreign_key(None, 'presets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ALEMBIC-4 fix: drop_constraint(None) невозможен — используем raw SQL для поиска и удаления FK по таблице+колонке
    op.execute("""
        DO $$
        DECLARE r RECORD;
        BEGIN
            FOR r IN
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_name = 'presets'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND kcu.column_name = 'user_id'
            LOOP
                EXECUTE 'ALTER TABLE presets DROP CONSTRAINT ' || quote_ident(r.constraint_name);
            END LOOP;
        END $$;
    """)
    op.drop_index(op.f('ix_presets_user_id'), table_name='presets')
    op.drop_column('presets', 'user_id')

