"""add_user_saved_presets_table

Revision ID: 572fc7e611e3
Revises: 47f92b78c02f
Create Date: 2025-11-01 09:06:23.744798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572fc7e611e3'
down_revision: Union[str, None] = '47f92b78c02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_saved_presets_id'), 'user_saved_presets', ['id'], unique=False)
    op.create_index(op.f('ix_user_saved_presets_preset_id'), 'user_saved_presets', ['preset_id'], unique=False)
    op.create_index(op.f('ix_user_saved_presets_user_id'), 'user_saved_presets', ['user_id'], unique=False)
    op.create_index('ix_user_saved_presets_user_preset_unique', 'user_saved_presets', ['user_id', 'preset_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_saved_presets_user_preset_unique', table_name='user_saved_presets')
    op.drop_index(op.f('ix_user_saved_presets_user_id'), table_name='user_saved_presets')
    op.drop_index(op.f('ix_user_saved_presets_preset_id'), table_name='user_saved_presets')
    op.drop_index(op.f('ix_user_saved_presets_id'), table_name='user_saved_presets')
    op.drop_table('user_saved_presets')
    # ### end Alembic commands ###



