"""add_printer_model

Revision ID: 9736e0b184e0
Revises: 0b9a467f6918
Create Date: 2025-10-31 14:39:31.493921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9736e0b184e0'
down_revision: Union[str, None] = '0b9a467f6918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('build_volume_x', sa.Float(), nullable=True),
    sa.Column('build_volume_y', sa.Float(), nullable=True),
    sa.Column('build_volume_z', sa.Float(), nullable=True),
    sa.Column('nozzle_diameter', sa.Float(), nullable=True),
    sa.Column('max_extruder_temp', sa.Integer(), nullable=True),
    sa.Column('max_bed_temp', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_active'), 'printers', ['active'], unique=False)
    op.create_index(op.f('ix_printers_id'), 'printers', ['id'], unique=False)
    op.create_index(op.f('ix_printers_manufacturer'), 'printers', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_printers_name'), 'printers', ['name'], unique=False)
    op.create_index(op.f('ix_printers_slug'), 'printers', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printers_slug'), table_name='printers')
    op.drop_index(op.f('ix_printers_name'), table_name='printers')
    op.drop_index(op.f('ix_printers_manufacturer'), table_name='printers')
    op.drop_index(op.f('ix_printers_id'), table_name='printers')
    op.drop_index(op.f('ix_printers_active'), table_name='printers')
    op.drop_table('printers')
    # ### end Alembic commands ###

