"""Add filament_reviews table and statistics fields

Revision ID: 97585b264440
Revises: d1b87bd1b8f7
Create Date: 2025-11-01 09:06:21.202293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97585b264440'
down_revision: Union[str, None] = 'd1b87bd1b8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filament_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('printer_model', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filament_reviews_active'), 'filament_reviews', ['active'], unique=False)
    op.create_index(op.f('ix_filament_reviews_filament_id'), 'filament_reviews', ['filament_id'], unique=False)
    op.create_index(op.f('ix_filament_reviews_id'), 'filament_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_filament_reviews_user_id'), 'filament_reviews', ['user_id'], unique=False)
    op.add_column('filaments', sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('filaments', sa.Column('scans_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filaments', 'scans_count')
    op.drop_column('filaments', 'views_count')
    op.drop_index(op.f('ix_filament_reviews_user_id'), table_name='filament_reviews')
    op.drop_index(op.f('ix_filament_reviews_id'), table_name='filament_reviews')
    op.drop_index(op.f('ix_filament_reviews_filament_id'), table_name='filament_reviews')
    op.drop_index(op.f('ix_filament_reviews_active'), table_name='filament_reviews')
    op.drop_table('filament_reviews')
    # ### end Alembic commands ###

