"""add_brand_requests_table

Revision ID: a1b2c3d4e5f6
Revises: 97585b264440
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '572fc7e611e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Create ENUM types for brand requests (check if they exist first)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE brandrequesttype AS ENUM ('join', 'create');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE brandrequeststatus AS ENUM ('pending', 'approved', 'rejected');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Создаем таблицу через SQL для надежности (как в статье на Хабре)
    # Используем DO блок для проверки существования таблицы
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'brand_requests'
            ) THEN
                CREATE TABLE brand_requests (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id),
                    request_type brandrequesttype NOT NULL,
                    brand_id INTEGER REFERENCES brands(id),
                    new_brand_name VARCHAR(100),
                    new_brand_slug VARCHAR(100),
                    new_brand_description TEXT,
                    new_brand_website VARCHAR(255),
                    message TEXT,
                    proof_text TEXT,
                    company_email VARCHAR(255),
                    company_website VARCHAR(500),
                    social_media_urls TEXT,
                    proof_files TEXT,
                    status brandrequeststatus NOT NULL DEFAULT 'pending',
                    processed_by_id INTEGER REFERENCES users(id),
                    processed_at TIMESTAMP,
                    rejection_reason TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT now(),
                    updated_at TIMESTAMP NOT NULL DEFAULT now()
                );
                
                CREATE INDEX IF NOT EXISTS ix_brand_requests_id ON brand_requests(id);
                CREATE INDEX IF NOT EXISTS ix_brand_requests_user_id ON brand_requests(user_id);
                CREATE INDEX IF NOT EXISTS ix_brand_requests_request_type ON brand_requests(request_type);
                CREATE INDEX IF NOT EXISTS ix_brand_requests_brand_id ON brand_requests(brand_id);
                CREATE INDEX IF NOT EXISTS ix_brand_requests_status ON brand_requests(status);
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_requests_status'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_brand_id'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_request_type'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_user_id'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_id'), table_name='brand_requests')
    op.drop_table('brand_requests')
    op.execute("DROP TYPE brandrequeststatus")
    op.execute("DROP TYPE brandrequesttype")
    # ### end Alembic commands ###

