"""add_brand_requests_table

Revision ID: a1b2c3d4e5f6
Revises: 97585b264440
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '572fc7e611e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Create ENUM types for brand requests (check if they exist first)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE brandrequesttype AS ENUM ('join', 'create');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE brandrequeststatus AS ENUM ('pending', 'approved', 'rejected');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Check if table exists before creating it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'brand_requests' not in inspector.get_table_names():
        op.create_table('brand_requests',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('request_type', sa.Enum('join', 'create', name='brandrequesttype', create_type=False), nullable=False),
            sa.Column('brand_id', sa.Integer(), nullable=True),
            sa.Column('new_brand_name', sa.String(length=100), nullable=True),
            sa.Column('new_brand_slug', sa.String(length=100), nullable=True),
            sa.Column('new_brand_description', sa.Text(), nullable=True),
            sa.Column('new_brand_website', sa.String(length=255), nullable=True),
            sa.Column('message', sa.Text(), nullable=True),
            sa.Column('proof_text', sa.Text(), nullable=True),
            sa.Column('company_email', sa.String(length=255), nullable=True),
            sa.Column('company_website', sa.String(length=500), nullable=True),
            sa.Column('social_media_urls', sa.Text(), nullable=True),
            sa.Column('proof_files', sa.Text(), nullable=True),
            sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='brandrequeststatus', create_type=False), nullable=False, server_default='pending'),
            sa.Column('processed_by_id', sa.Integer(), nullable=True),
            sa.Column('processed_at', sa.DateTime(), nullable=True),
            sa.Column('rejection_reason', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
            sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_brand_requests_id'), 'brand_requests', ['id'], unique=False)
        op.create_index(op.f('ix_brand_requests_user_id'), 'brand_requests', ['user_id'], unique=False)
        op.create_index(op.f('ix_brand_requests_request_type'), 'brand_requests', ['request_type'], unique=False)
        op.create_index(op.f('ix_brand_requests_brand_id'), 'brand_requests', ['brand_id'], unique=False)
        op.create_index(op.f('ix_brand_requests_status'), 'brand_requests', ['status'], unique=False)
    else:
        # Table exists, but check indexes
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('brand_requests')]
        if 'ix_brand_requests_id' not in existing_indexes:
            op.create_index(op.f('ix_brand_requests_id'), 'brand_requests', ['id'], unique=False)
        if 'ix_brand_requests_user_id' not in existing_indexes:
            op.create_index(op.f('ix_brand_requests_user_id'), 'brand_requests', ['user_id'], unique=False)
        if 'ix_brand_requests_request_type' not in existing_indexes:
            op.create_index(op.f('ix_brand_requests_request_type'), 'brand_requests', ['request_type'], unique=False)
        if 'ix_brand_requests_brand_id' not in existing_indexes:
            op.create_index(op.f('ix_brand_requests_brand_id'), 'brand_requests', ['brand_id'], unique=False)
        if 'ix_brand_requests_status' not in existing_indexes:
            op.create_index(op.f('ix_brand_requests_status'), 'brand_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_requests_status'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_brand_id'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_request_type'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_user_id'), table_name='brand_requests')
    op.drop_index(op.f('ix_brand_requests_id'), table_name='brand_requests')
    op.drop_table('brand_requests')
    op.execute("DROP TYPE brandrequeststatus")
    op.execute("DROP TYPE brandrequesttype")
    # ### end Alembic commands ###

