"""Add printer_id to users, material_mappings and preset_printers tables

Revision ID: cd4a3c3232ff
Revises: b3c4d5e6f7a8
Create Date: 2025-11-03 11:32:22.786365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd4a3c3232ff'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=False),
    sa.Column('orcaslicer_preset', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Enum('automatic', 'manual', 'brand', name='materialmappingpriority'), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_mappings_active'), 'material_mappings', ['active'], unique=False)
    op.create_index(op.f('ix_material_mappings_brand_id'), 'material_mappings', ['brand_id'], unique=False)
    op.create_index(op.f('ix_material_mappings_id'), 'material_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_material_mappings_material_type'), 'material_mappings', ['material_type'], unique=False)
    op.create_index(op.f('ix_material_mappings_priority'), 'material_mappings', ['priority'], unique=False)
    op.create_table('preset_printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preset_printers_id'), 'preset_printers', ['id'], unique=False)
    op.create_index(op.f('ix_preset_printers_is_primary'), 'preset_printers', ['is_primary'], unique=False)
    op.create_index(op.f('ix_preset_printers_preset_id'), 'preset_printers', ['preset_id'], unique=False)
    op.create_index(op.f('ix_preset_printers_printer_id'), 'preset_printers', ['printer_id'], unique=False)
    op.alter_column('brand_requests', 'request_type',
               existing_type=postgresql.ENUM('join', 'create', name='brandrequesttype'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('brand_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='brandrequeststatus'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::brandrequeststatus"))
    op.drop_index('ix_user_saved_presets_user_preset_unique', table_name='user_saved_presets')
    op.add_column('users', sa.Column('printer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_printer_id'), 'users', ['printer_id'], unique=False)
    op.create_foreign_key(None, 'users', 'printers', ['printer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_printer_id'), table_name='users')
    op.drop_column('users', 'printer_id')
    op.create_index('ix_user_saved_presets_user_preset_unique', 'user_saved_presets', ['user_id', 'preset_id'], unique=True)
    op.alter_column('brand_requests', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='brandrequeststatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::brandrequeststatus"))
    op.alter_column('brand_requests', 'request_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('join', 'create', name='brandrequesttype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_preset_printers_printer_id'), table_name='preset_printers')
    op.drop_index(op.f('ix_preset_printers_preset_id'), table_name='preset_printers')
    op.drop_index(op.f('ix_preset_printers_is_primary'), table_name='preset_printers')
    op.drop_index(op.f('ix_preset_printers_id'), table_name='preset_printers')
    op.drop_table('preset_printers')
    op.drop_index(op.f('ix_material_mappings_priority'), table_name='material_mappings')
    op.drop_index(op.f('ix_material_mappings_material_type'), table_name='material_mappings')
    op.drop_index(op.f('ix_material_mappings_id'), table_name='material_mappings')
    op.drop_index(op.f('ix_material_mappings_brand_id'), table_name='material_mappings')
    op.drop_index(op.f('ix_material_mappings_active'), table_name='material_mappings')
    op.drop_table('material_mappings')
    # ### end Alembic commands ###

