"""restore unique (user_id, preset_id) on user_saved_presets

The unique index created by 572fc7e611e3 was dropped by the autogenerated
cd4a3c3232ff (the model never declared it, so autogenerate treated it as
removed). Since then duplicate saved rows are only prevented by a pre-SELECT
in the API, which does not survive concurrent requests, while the Orca sync
import already handles IntegrityError expecting this constraint.

Revision ID: usp_user_preset_unique_restore
Revises: spool_single_location
Create Date: 2026-07-17
"""

from collections.abc import Sequence

from alembic import op

revision: str = "usp_user_preset_unique_restore"
down_revision: str | None = "spool_single_location"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Preflight: collapse duplicates that may have accumulated while the
    # constraint was missing — keep the freshest row per (user, preset).
    op.execute(
        """
        DELETE FROM user_saved_presets AS usp
        USING (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY user_id, preset_id
                       ORDER BY saved_at DESC, id DESC
                   ) AS rn
            FROM user_saved_presets
        ) ranked
        WHERE usp.id = ranked.id AND ranked.rn > 1
        """
    )
    # Historical name from 572fc7e611e3, matching the model declaration.
    op.create_index(
        "ix_user_saved_presets_user_preset_unique",
        "user_saved_presets",
        ["user_id", "preset_id"],
        unique=True,
    )


def downgrade() -> None:
    # The dedup is data cleanup and is not reverted.
    op.drop_index(
        "ix_user_saved_presets_user_preset_unique", table_name="user_saved_presets"
    )
