"""Централизованные русскоязычные сообщения об ошибках для HTTP-ответов."""

# 404 — Не найдено
ERR_USER_NOT_FOUND = "Пользователь не найден"
ERR_BRAND_NOT_FOUND = "Бренд не найден"
ERR_PRESET_NOT_FOUND = "Пресет не найден"
ERR_FILAMENT_NOT_FOUND = "Материал не найден"
ERR_PRINTER_NOT_FOUND = "Принтер не найден"
ERR_REQUEST_NOT_FOUND = "Заявка не найдена"
ERR_NOTIFICATION_NOT_FOUND = "Уведомление не найдено"
ERR_FEEDBACK_NOT_FOUND = "Обратная связь не найдена"
ERR_REVIEW_NOT_FOUND = "Отзыв не найден"
ERR_ARTICLE_NOT_FOUND = "Статья не найдена"
ERR_CATEGORY_NOT_FOUND = "Категория не найдена"
ERR_PRINT_PROFILE_NOT_FOUND = "Профиль печати не найден"
ERR_PRINTER_PROFILE_NOT_FOUND = "Профиль принтера не найден"
ERR_PRINTER_REQUEST_NOT_FOUND = "Заявка на принтер не найдена"
ERR_BRAND_REQUEST_NOT_FOUND = "Заявка на бренд не найдена"
ERR_SAVED_PRESET_NOT_FOUND = "Сохранённый пресет не найден"
ERR_OFFICIAL_PRESET_NOT_FOUND = "Официальный пресет не найден"
ERR_QR_NOT_FOUND = "QR-код не найден"
ERR_HELPFUL_MARK_NOT_FOUND = "Отметка полезности не найдена"
ERR_BANNED_WORD_NOT_FOUND = "Запрещённое слово не найдено"
ERR_DUMP_NOT_FOUND = "Файл дампа не найден"
ERR_TABLE_NOT_FOUND = "Таблица не найдена"
ERR_FILE_NOT_FOUND_IN_REQUEST = "Файл не найден в заявке"
ERR_ARTICLE_NOT_PUBLISHED = "Статья не опубликована"

# 400 — Дублирование / конфликт
ERR_BRAND_SLUG_EXISTS = "Бренд с таким slug уже существует"
ERR_PRINTER_SLUG_EXISTS = "Принтер с таким slug уже существует"
ERR_EMAIL_EXISTS = "Email уже зарегистрирован"
ERR_USERNAME_EXISTS = "Имя пользователя уже занято"
ERR_USER_ALREADY_IN_BRAND = "Пользователь уже привязан к бренду"
ERR_USER_NOT_IN_BRAND = "Пользователь не привязан к бренду"
ERR_REQUEST_NOT_PENDING = "Можно изменять только ожидающие заявки"
ERR_SLUG_EXISTS = "Slug уже существует"
ERR_CATEGORY_SLUG_EXISTS = "Категория с таким slug уже существует"
ERR_CATEGORY_NAME_EXISTS = "Категория с таким именем уже существует"
ERR_CATEGORY_SLUG_OR_NAME_EXISTS = "Категория с таким slug или именем уже существует"
ERR_ARTICLE_SLUG_EXISTS = "Статья с таким slug уже существует"
ERR_PRESET_INACTIVE = "Нельзя сохранить неактивный пресет"
ERR_PRINTER_REQUEST_PENDING = "Запрос на добавление этого принтера уже существует и ожидает рассмотрения"
ERR_BRAND_REQUEST_PENDING_JOIN = "У вас уже есть ожидающая заявка на вступление в этот бренд"
ERR_BRAND_REQUEST_PENDING_CREATE = "У вас уже есть ожидающая заявка на создание этого бренда"
ERR_ALREADY_HELPFUL = "Вы уже отметили эту статью как полезную"
ERR_ALREADY_FEEDBACK = "Вы уже оставили обратную связь для этой статьи"
ERR_FILAMENT_NO_PRESETS = "Материал не найден или нет доступных пресетов"

# 401 — Аутентификация
ERR_INVALID_CREDENTIALS = "Неверный email/логин или пароль"
ERR_INVALID_REFRESH_TOKEN = "Токен обновления недействителен или истёк"
ERR_INVALID_VERIFICATION_TOKEN = "Токен верификации недействителен или истёк"
ERR_AUTH_REQUIRED = "Для этого действия необходима авторизация"

# 403 — Права доступа
ERR_ACCOUNT_INACTIVE = "Аккаунт пользователя неактивен"
ERR_ACCESS_DENIED = "Доступ запрещён"
ERR_NO_PERMISSION = "Недостаточно прав"
ERR_ONLY_ADMIN_OFFICIAL = "Только администраторы могут устанавливать официальный статус"
ERR_ONLY_ADMIN_REASSIGN = "Только администраторы могут менять владельца"
ERR_CANNOT_ASSIGN_OTHER_OWNER = "Нельзя назначить владельцем другого пользователя"
ERR_QR_VERIFIED_ONLY = "QR-код может быть сгенерирован только для верифицированных брендов"
ERR_NO_PERMISSION_CREATE_FILAMENT = "Недостаточно прав. Вы можете создавать материалы только для своего бренда."
ERR_NO_PERMISSION_EDIT_FILAMENT = "Недостаточно прав. Вы можете редактировать материалы только своего бренда."
ERR_NO_PERMISSION_DELETE_FILAMENT = "Недостаточно прав. Вы можете удалять материалы только своего бренда."
ERR_NO_PERMISSION_EDIT_PRESET = "Вы можете редактировать только свои пресеты"
ERR_NO_PERMISSION_DELETE_PRESET = "Вы можете удалять только свои пресеты"
ERR_NO_PERMISSION_EDIT_REVIEW = "Нет прав на изменение этого отзыва"
ERR_NO_PERMISSION_DELETE_REVIEW = "Нет прав на удаление этого отзыва"
ERR_WEIGHTED_PRESET_READONLY = "Взвешенные пресеты нельзя редактировать напрямую"
ERR_WEIGHTED_PRESET_NO_DELETE = "Взвешенные пресеты нельзя удалять напрямую"

# 500 — Серверные ошибки
ERR_INTERNAL_ERROR = "Внутренняя ошибка сервера"
