"""Centralized error codes for HTTP responses (i18n-ready)."""

from typing import NoReturn

from fastapi import HTTPException

# 404 — Not found
ERR_USER_NOT_FOUND = "ERR_USER_NOT_FOUND"
ERR_BRAND_NOT_FOUND = "ERR_BRAND_NOT_FOUND"
ERR_PRESET_NOT_FOUND = "ERR_PRESET_NOT_FOUND"
ERR_FILAMENT_NOT_FOUND = "ERR_FILAMENT_NOT_FOUND"
ERR_FILAMENT_LINE_NOT_FOUND = "ERR_FILAMENT_LINE_NOT_FOUND"
ERR_FILAMENT_LINE_INVALID = "ERR_FILAMENT_LINE_INVALID"
ERR_PRINTER_NOT_FOUND = "ERR_PRINTER_NOT_FOUND"
ERR_REQUEST_NOT_FOUND = "ERR_REQUEST_NOT_FOUND"
ERR_NOTIFICATION_NOT_FOUND = "ERR_NOTIFICATION_NOT_FOUND"
ERR_FEEDBACK_NOT_FOUND = "ERR_FEEDBACK_NOT_FOUND"
ERR_REVIEW_NOT_FOUND = "ERR_REVIEW_NOT_FOUND"
ERR_ARTICLE_NOT_FOUND = "ERR_ARTICLE_NOT_FOUND"
ERR_CATEGORY_NOT_FOUND = "ERR_CATEGORY_NOT_FOUND"
ERR_PRINT_PROFILE_NOT_FOUND = "ERR_PRINT_PROFILE_NOT_FOUND"
ERR_PRINTER_PROFILE_NOT_FOUND = "ERR_PRINTER_PROFILE_NOT_FOUND"
ERR_PRINTER_REQUEST_NOT_FOUND = "ERR_PRINTER_REQUEST_NOT_FOUND"
ERR_BRAND_REQUEST_NOT_FOUND = "ERR_BRAND_REQUEST_NOT_FOUND"
ERR_BRAND_INVITE_NOT_FOUND = "ERR_BRAND_INVITE_NOT_FOUND"
ERR_BRAND_INVITE_INVALID = "ERR_BRAND_INVITE_INVALID"
ERR_SAVED_PRESET_NOT_FOUND = "ERR_SAVED_PRESET_NOT_FOUND"
ERR_OFFICIAL_PRESET_NOT_FOUND = "ERR_OFFICIAL_PRESET_NOT_FOUND"
ERR_QR_NOT_FOUND = "ERR_QR_NOT_FOUND"
ERR_HELPFUL_MARK_NOT_FOUND = "ERR_HELPFUL_MARK_NOT_FOUND"
ERR_BANNED_WORD_NOT_FOUND = "ERR_BANNED_WORD_NOT_FOUND"
ERR_DUMP_NOT_FOUND = "ERR_DUMP_NOT_FOUND"
ERR_TABLE_NOT_FOUND = "ERR_TABLE_NOT_FOUND"
ERR_FILE_NOT_FOUND_IN_REQUEST = "ERR_FILE_NOT_FOUND_IN_REQUEST"
ERR_ARTICLE_NOT_PUBLISHED = "ERR_ARTICLE_NOT_PUBLISHED"
ERR_CALCULATOR_HISTORY_NOT_FOUND = "ERR_CALCULATOR_HISTORY_NOT_FOUND"
ERR_SHARED_QUOTE_NOT_FOUND = "ERR_SHARED_QUOTE_NOT_FOUND"
ERR_SHARED_QUOTE_EXPIRED = "ERR_SHARED_QUOTE_EXPIRED"
ERR_PDF_GENERATION_FAILED = "ERR_PDF_GENERATION_FAILED"

# 400 — Duplicate / conflict
ERR_BRAND_SLUG_EXISTS = "ERR_BRAND_SLUG_EXISTS"
ERR_PRINTER_SLUG_EXISTS = "ERR_PRINTER_SLUG_EXISTS"
ERR_EMAIL_EXISTS = "ERR_EMAIL_EXISTS"
ERR_USERNAME_EXISTS = "ERR_USERNAME_EXISTS"
ERR_USER_ALREADY_IN_BRAND = "ERR_USER_ALREADY_IN_BRAND"
ERR_USER_NOT_IN_BRAND = "ERR_USER_NOT_IN_BRAND"
ERR_REQUEST_NOT_PENDING = "ERR_REQUEST_NOT_PENDING"
ERR_SLUG_EXISTS = "ERR_SLUG_EXISTS"
ERR_CATEGORY_SLUG_EXISTS = "ERR_CATEGORY_SLUG_EXISTS"
ERR_CATEGORY_NAME_EXISTS = "ERR_CATEGORY_NAME_EXISTS"
ERR_CATEGORY_SLUG_OR_NAME_EXISTS = "ERR_CATEGORY_SLUG_OR_NAME_EXISTS"
ERR_ARTICLE_SLUG_EXISTS = "ERR_ARTICLE_SLUG_EXISTS"
ERR_PRESET_INACTIVE = "ERR_PRESET_INACTIVE"
ERR_PRINTER_REQUEST_PENDING = "ERR_PRINTER_REQUEST_PENDING"
ERR_BRAND_REQUEST_PENDING_JOIN = "ERR_BRAND_REQUEST_PENDING_JOIN"
ERR_BRAND_REQUEST_PENDING_CREATE = "ERR_BRAND_REQUEST_PENDING_CREATE"
ERR_ALREADY_HELPFUL = "ERR_ALREADY_HELPFUL"
ERR_ALREADY_FEEDBACK = "ERR_ALREADY_FEEDBACK"
ERR_FILAMENT_NO_PRESETS = "ERR_FILAMENT_NO_PRESETS"
ERR_FILAMENT_ALREADY_EXISTS = "ERR_FILAMENT_ALREADY_EXISTS"

# 401 — Authentication
ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS"
ERR_INVALID_REFRESH_TOKEN = "ERR_INVALID_REFRESH_TOKEN"
ERR_INVALID_VERIFICATION_TOKEN = "ERR_INVALID_VERIFICATION_TOKEN"
ERR_AUTH_REQUIRED = "ERR_AUTH_REQUIRED"
ERR_OAUTH_FAILED = "ERR_OAUTH_FAILED"                   # params: {provider}
ERR_OAUTH_INVALID_STATE = "ERR_OAUTH_INVALID_STATE"
ERR_OAUTH_EMAIL_MISSING = "ERR_OAUTH_EMAIL_MISSING"      # params: {provider}

# 400 — OAuth
ERR_OAUTH_PROVIDER_NOT_CONFIGURED = "ERR_OAUTH_PROVIDER_NOT_CONFIGURED"  # params: {provider}
ERR_OAUTH_INVALID_PROVIDER = "ERR_OAUTH_INVALID_PROVIDER"  # params: {provider}
ERR_OAUTH_EMAIL_TAKEN = "ERR_OAUTH_EMAIL_TAKEN"          # params: {provider}

# 403 — Permissions
ERR_ACCOUNT_INACTIVE = "ERR_ACCOUNT_INACTIVE"
ERR_ACCESS_DENIED = "ERR_ACCESS_DENIED"
ERR_NO_PERMISSION = "ERR_NO_PERMISSION"
ERR_ONLY_ADMIN_OFFICIAL = "ERR_ONLY_ADMIN_OFFICIAL"
ERR_ONLY_ADMIN_REASSIGN = "ERR_ONLY_ADMIN_REASSIGN"
ERR_CANNOT_ASSIGN_OTHER_OWNER = "ERR_CANNOT_ASSIGN_OTHER_OWNER"
ERR_QR_VERIFIED_ONLY = "ERR_QR_VERIFIED_ONLY"
ERR_NO_PERMISSION_CREATE_FILAMENT = "ERR_NO_PERMISSION_CREATE_FILAMENT"
ERR_NO_PERMISSION_EDIT_FILAMENT = "ERR_NO_PERMISSION_EDIT_FILAMENT"
ERR_NO_PERMISSION_DELETE_FILAMENT = "ERR_NO_PERMISSION_DELETE_FILAMENT"
ERR_NO_PERMISSION_EDIT_PRESET = "ERR_NO_PERMISSION_EDIT_PRESET"
ERR_NO_PERMISSION_DELETE_PRESET = "ERR_NO_PERMISSION_DELETE_PRESET"
ERR_NO_PERMISSION_EDIT_REVIEW = "ERR_NO_PERMISSION_EDIT_REVIEW"
ERR_NO_PERMISSION_DELETE_REVIEW = "ERR_NO_PERMISSION_DELETE_REVIEW"
ERR_WEIGHTED_PRESET_READONLY = "ERR_WEIGHTED_PRESET_READONLY"
ERR_WEIGHTED_PRESET_NO_DELETE = "ERR_WEIGHTED_PRESET_NO_DELETE"

# 500 — Server errors
ERR_INTERNAL_ERROR = "ERR_INTERNAL_ERROR"

# --- New constants for hardcoded strings ---

# auth.py
ERR_RECAPTCHA_FAILED = "ERR_RECAPTCHA_FAILED"
ERR_PASSWORD_HASH_ERROR = "ERR_PASSWORD_HASH_ERROR"
ERR_USER_CREATE_ERROR = "ERR_USER_CREATE_ERROR"
ERR_RESPONSE_ERROR = "ERR_RESPONSE_ERROR"
ERR_WRONG_PASSWORD = "ERR_WRONG_PASSWORD"
ERR_INVALID_RESET_TOKEN = "ERR_INVALID_RESET_TOKEN"
ERR_EMAIL_MISMATCH = "ERR_EMAIL_MISMATCH"
ERR_ACCOUNT_BLOCKED = "ERR_ACCOUNT_BLOCKED"

# dependencies.py
ERR_COULD_NOT_VALIDATE = "ERR_COULD_NOT_VALIDATE"
ERR_USER_INACTIVE = "ERR_USER_INACTIVE"
ERR_NOT_BRAND_USER = "ERR_NOT_BRAND_USER"
ERR_NOT_ADMIN = "ERR_NOT_ADMIN"
ERR_INVALID_API_KEY = "ERR_INVALID_API_KEY"

# email_validator.py (with params)
ERR_EMAIL_DOMAIN_TYPO = "ERR_EMAIL_DOMAIN_TYPO"         # params: {domain}
ERR_DOMAIN_NO_MAIL = "ERR_DOMAIN_NO_MAIL"               # params: {domain}

# admin.py
ERR_BRAND_ID_REQUIRED_JOIN = "ERR_BRAND_ID_REQUIRED_JOIN"
ERR_BRAND_NAME_SLUG_REQUIRED = "ERR_BRAND_NAME_SLUG_REQUIRED"
ERR_FILENAME_REQUIRED = "ERR_FILENAME_REQUIRED"
ERR_DB_IMPORT_ERROR = "ERR_DB_IMPORT_ERROR"
ERR_INVALID_FILENAME = "ERR_INVALID_FILENAME"
ERR_TABLE_STRUCTURE_ERROR = "ERR_TABLE_STRUCTURE_ERROR"
ERR_TABLE_DATA_ERROR = "ERR_TABLE_DATA_ERROR"
ERR_PRIMARY_KEY_REQUIRED = "ERR_PRIMARY_KEY_REQUIRED"
ERR_DATA_REQUIRED = "ERR_DATA_REQUIRED"
ERR_TABLE_UPDATE_ERROR = "ERR_TABLE_UPDATE_ERROR"
ERR_TABLE_DELETE_ERROR = "ERR_TABLE_DELETE_ERROR"
ERR_USER_IDS_EMPTY = "ERR_USER_IDS_EMPTY"
ERR_NO_ACTIVE_USERS_FOUND = "ERR_NO_ACTIVE_USERS_FOUND"

# brand_requests.py
ERR_BRAND_ID_REQUIRED = "ERR_BRAND_ID_REQUIRED"
ERR_BRAND_CREATE_NAME_SLUG_REQUIRED = "ERR_BRAND_CREATE_NAME_SLUG_REQUIRED"
ERR_DOCUMENTS_REQUIRED = "ERR_DOCUMENTS_REQUIRED"
ERR_VIEW_OWN_REQUESTS_ONLY = "ERR_VIEW_OWN_REQUESTS_ONLY"
ERR_UPLOAD_OWN_REQUESTS_ONLY = "ERR_UPLOAD_OWN_REQUESTS_ONLY"
ERR_DELETE_OWN_FILES_ONLY = "ERR_DELETE_OWN_FILES_ONLY"

# calculator.py
ERR_WEIGHT_REQUIRED = "ERR_WEIGHT_REQUIRED"
ERR_SPOOL_PRICE_REQUIRED = "ERR_SPOOL_PRICE_REQUIRED"
ERR_TIME_REQUIRED = "ERR_TIME_REQUIRED"
ERR_PRICE_PER_HOUR_REQUIRED = "ERR_PRICE_PER_HOUR_REQUIRED"
ERR_GCODE_PARSE_FAILED = "ERR_GCODE_PARSE_FAILED"

# filament_reviews.py
ERR_ADD_PRESET_FIRST = "ERR_ADD_PRESET_FIRST"
ERR_PRESET_NOT_MATCH = "ERR_PRESET_NOT_MATCH"
ERR_REVIEW_SAVED_ONLY = "ERR_REVIEW_SAVED_ONLY"
ERR_REVIEW_ALREADY_EXISTS = "ERR_REVIEW_ALREADY_EXISTS"

# orca_sync.py
ERR_EXPORT_PRINTER_DISABLED = "ERR_EXPORT_PRINTER_DISABLED"
ERR_EXPORT_PRINT_DISABLED = "ERR_EXPORT_PRINT_DISABLED"
ERR_IMPORT_PRINTER_DISABLED = "ERR_IMPORT_PRINTER_DISABLED"
ERR_IMPORT_PRINT_DISABLED = "ERR_IMPORT_PRINT_DISABLED"
ERR_IMPORT_FILAMENT_DISABLED = "ERR_IMPORT_FILAMENT_DISABLED"
ERR_TOO_MANY_PROFILES = "ERR_TOO_MANY_PROFILES"         # params: {count, max}
ERR_NO_NOTIFICATION_DATA = "ERR_NO_NOTIFICATION_DATA"
ERR_PRESET_IDS_REQUIRED = "ERR_PRESET_IDS_REQUIRED"

# presets.py / profiles
ERR_EXPORT_PRESET_ERROR = "ERR_EXPORT_PRESET_ERROR"
ERR_EXPORT_PRINT_PROFILE_ERROR = "ERR_EXPORT_PRINT_PROFILE_ERROR"
ERR_EXPORT_PRINTER_PROFILE_ERROR = "ERR_EXPORT_PRINTER_PROFILE_ERROR"
ERR_ONLY_BRAND_OFFICIAL = "ERR_ONLY_BRAND_OFFICIAL"
ERR_ONLY_OWN_BRAND_OFFICIAL = "ERR_ONLY_OWN_BRAND_OFFICIAL"
ERR_OFFICIAL_VERIFIED_ONLY = "ERR_OFFICIAL_VERIFIED_ONLY"
ERR_CUSTOM_FILLER_VERIFIED_ONLY = "ERR_CUSTOM_FILLER_VERIFIED_ONLY"

# file_service.py (with params)
ERR_FILE_EXT_NOT_ALLOWED = "ERR_FILE_EXT_NOT_ALLOWED"    # params: {ext, allowed}
ERR_MAX_FILES_EXCEEDED = "ERR_MAX_FILES_EXCEEDED"         # params: {max}
ERR_FILE_SIZE_EXCEEDED = "ERR_FILE_SIZE_EXCEEDED"         # params: {size_mb, max_mb}
ERR_INVALID_FILE_PATH = "ERR_INVALID_FILE_PATH"
ERR_FILE_SAVE_FAILED = "ERR_FILE_SAVE_FAILED"
ERR_FILE_CONTENT_MISMATCH = "ERR_FILE_CONTENT_MISMATCH"   # params: {ext}

# printer_requests.py
ERR_UPLOAD_PENDING_ONLY = "ERR_UPLOAD_PENDING_ONLY"
ERR_DELETE_PENDING_ONLY = "ERR_DELETE_PENDING_ONLY"

# misc
ERR_BAD_WORDS = "ERR_BAD_WORDS"                           # params: {field_name}
ERR_REPEATED_CHARS = "ERR_REPEATED_CHARS"                 # params: {field_name}
ERR_NO_LETTERS_OR_DIGITS = "ERR_NO_LETTERS_OR_DIGITS"     # params: {field_name}

# preset validation (validate_preset_settings)
ERR_EXTRUDER_TEMP_TOO_LOW = "ERR_EXTRUDER_TEMP_TOO_LOW"   # params: {value, min}
ERR_EXTRUDER_TEMP_TOO_HIGH = "ERR_EXTRUDER_TEMP_TOO_HIGH" # params: {value, max}
ERR_BED_TEMP_TOO_LOW = "ERR_BED_TEMP_TOO_LOW"             # params: {value, min}
ERR_BED_TEMP_TOO_HIGH = "ERR_BED_TEMP_TOO_HIGH"           # params: {value, max}
ERR_PRINT_SPEED_TOO_LOW = "ERR_PRINT_SPEED_TOO_LOW"       # params: {value, min}
ERR_PRINT_SPEED_TOO_HIGH = "ERR_PRINT_SPEED_TOO_HIGH"     # params: {value, max}
ERR_FAN_SPEED_TOO_LOW = "ERR_FAN_SPEED_TOO_LOW"           # params: {value, min, max}
ERR_FAN_SPEED_TOO_HIGH = "ERR_FAN_SPEED_TOO_HIGH"         # params: {value, min, max}
ERR_RETRACTION_LEN_TOO_LOW = "ERR_RETRACTION_LEN_TOO_LOW"   # params: {value, min, max}
ERR_RETRACTION_LEN_TOO_HIGH = "ERR_RETRACTION_LEN_TOO_HIGH" # params: {value, max}
ERR_RETRACTION_SPEED_TOO_LOW = "ERR_RETRACTION_SPEED_TOO_LOW"   # params: {value, min}
ERR_RETRACTION_SPEED_TOO_HIGH = "ERR_RETRACTION_SPEED_TOO_HIGH" # params: {value, max}
ERR_BED_TEMP_EXCEEDS_EXTRUDER = "ERR_BED_TEMP_EXCEEDS_EXTRUDER" # params: {bed_temp, extruder_temp}
ERR_DOWNLOAD_UNAVAILABLE = "ERR_DOWNLOAD_UNAVAILABLE"     # params: {platform, arch, type}
ERR_INVALID_FEEDBACK_TYPE = "ERR_INVALID_FEEDBACK_TYPE"
ERR_INVALID_FEEDBACK_STATUS = "ERR_INVALID_FEEDBACK_STATUS"
ERR_WIKI_USE_FEEDBACK = "ERR_WIKI_USE_FEEDBACK"
ERR_BANNED_WORD_EXISTS = "ERR_BANNED_WORD_EXISTS"         # params: {word, language}
ERR_INVALID_BADGES = "ERR_INVALID_BADGES"                 # params: {invalid, valid}
ERR_INVALID_FILE_EXT = "ERR_INVALID_FILE_EXT"             # params: {ext, expected}
ERR_FILE_TOO_LARGE = "ERR_FILE_TOO_LARGE"                 # params: {max_size}
ERR_UNSUPPORTED_PRICING_METHOD = "ERR_UNSUPPORTED_PRICING_METHOD"  # params: {method}
ERR_EXPORT_MISSING_FIELDS = "ERR_EXPORT_MISSING_FIELDS"    # params: {fields}

# preset_slot_sync / devices
ERR_DEVICE_NOT_FOUND = "ERR_DEVICE_NOT_FOUND"
ERR_DEVICE_NOT_OWNER = "ERR_DEVICE_NOT_OWNER"
ERR_GATE_INDEX_INVALID = "ERR_GATE_INDEX_INVALID"          # params: {gate, max}
ERR_GATE_STATE_NOT_FOUND = "ERR_GATE_STATE_NOT_FOUND"      # params: {gate}
ERR_PRESET_NOT_ACCESSIBLE = "ERR_PRESET_NOT_ACCESSIBLE"    # params: {preset_id}
ERR_PRESET_ALREADY_ACTIVE = "ERR_PRESET_ALREADY_ACTIVE"
ERR_PRESET_NOT_OWNER = "ERR_PRESET_NOT_OWNER"
ERR_SPOOL_NOT_ACCESSIBLE = "ERR_SPOOL_NOT_ACCESSIBLE"      # params: {spool_id}
ERR_SNAPSHOT_TOO_FREQUENT = "ERR_SNAPSHOT_TOO_FREQUENT"

# Catalog bundle import (admin-only seed of printer catalog from external slicer bundles)
ERR_BUNDLE_NOT_FOUND = "ERR_BUNDLE_NOT_FOUND"                      # params: {bundle_id}
ERR_BUNDLE_DUPLICATE = "ERR_BUNDLE_DUPLICATE"                      # params: {bundle_id, sha256}
ERR_BUNDLE_SOURCE_UNSUPPORTED = "ERR_BUNDLE_SOURCE_UNSUPPORTED"    # params: {source, allowed}
ERR_BUNDLE_SOURCE_NOT_IMPLEMENTED = "ERR_BUNDLE_SOURCE_NOT_IMPLEMENTED"  # params: {source}
ERR_BUNDLE_NOT_VALIDATED = "ERR_BUNDLE_NOT_VALIDATED"              # params: {bundle_id, status}
ERR_BUNDLE_IMPORT_FAILED = "ERR_BUNDLE_IMPORT_FAILED"              # params: {bundle_id, error}
ERR_BUNDLE_FILE_TOO_LARGE = "ERR_BUNDLE_FILE_TOO_LARGE"            # params: {size_mb, max_mb}
ERR_BUNDLE_FILE_REQUIRED = "ERR_BUNDLE_FILE_REQUIRED"

# Preset version history
ERR_PRESET_VERSION_NOT_FOUND = "ERR_PRESET_VERSION_NOT_FOUND"      # params: {version_id}
ERR_PRESET_VERSION_FORBIDDEN = "ERR_PRESET_VERSION_FORBIDDEN"      # params: {preset_id}


def raise_error(
    status_code: int,
    code: str,
    params: dict | None = None,
    headers: dict | None = None,
) -> NoReturn:
    """Raise HTTPException with structured error detail."""
    detail: dict = {"code": code}
    if params:
        detail["params"] = params
    raise HTTPException(status_code=status_code, detail=detail, headers=headers)
